(()=>{
const form=document.getElementById('order'),summary=document.getElementById('orderSummary'),button=document.getElementById('submitOrder'),message=document.getElementById('orderMsg');
const rub=n=>Number(n).toLocaleString('ru-RU')+' ₽',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cart=[],validCart=[],pending=null;
try{const saved=JSON.parse(localStorage.getItem('ps-cart')||'[]');if(Array.isArray(saved))cart=saved;pending=JSON.parse(sessionStorage.getItem('ps-order-pending')||'null')}catch(e){}
function addressState(){const needed=form.elements.delivery.value==='orenburg_delivery';document.getElementById('addressLabel').classList.toggle('hidden',!needed);form.elements.address.required=needed}
form.elements.delivery.onchange=addressState;addressState();form.elements.phone.oninput=()=>form.elements.phone.setCustomValidity('');
async function request(url,opts={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(url,{...opts,signal:controller.signal});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'server_error');return j}finally{clearTimeout(timer)}}
// Account prefill is optional and never blocks the cart.
request('api/customer.php?action=me',{cache:'no-store'}).then(j=>{if(j.customer)for(const key of ['name','email','phone'])if(!form.elements[key].value)form.elements[key].value=j.customer[key]||''}).catch(()=>{});
(async()=>{try{
const all=await loadRealCatalog(),byId=new Map(all.map(p=>[String(p.id),p])),groups=new Map;cart.forEach(id=>groups.set(String(id),(groups.get(String(id))||0)+1));let total=0,invalid=false;
const rows=[...groups].map(([id,qty])=>{const p=byId.get(id);const bad=!p||p.stockCode==='out'||p.price<=0||(p.stockQty!==null&&qty>p.stockQty);if(bad)invalid=true;else{for(let i=0;i<qty;i++)validCart.push(p.id);total+=p.price*qty}return `<div class="checkoutRow"><span>${esc(p?.name||'Недоступный товар')} × ${qty}${bad?'<br><strong>Товар недоступен, цена не задана или превышен остаток.</strong>':''}</span><span>${p?rub(p.price*qty):''} <button type="button" data-remove="${esc(id)}">Убрать</button></span></div>`}).join('');
summary.innerHTML=rows?`${rows}<div class="checkoutTotal">Сумма доступных товаров: <b>${rub(total)}</b></div>`:'<p>Корзина пуста. <a href="index.html">Перейти в каталог</a></p>';
summary.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(id=>String(id)!==b.dataset.remove);localStorage.setItem('ps-cart',JSON.stringify(cart));location.reload()});
button.disabled=invalid||!validCart.length;if(invalid)message.textContent='Уберите недоступные позиции перед оформлением.';
}catch(e){summary.textContent='Не удалось загрузить корзину. Обновите страницу для повторной попытки.';button.disabled=true}})();
const errors={invalid_input:'Проверьте имя и телефон: нужен номер из 11 цифр, начинающийся с 7 или 8.',bad_email:'Проверьте адрес электронной почты.',address_required:'Укажите адрес доставки.',out_of_stock:'Товар закончился. Обновите корзину.',insufficient_stock:'Заказанное количество превышает остаток. Обновите корзину.',price_unavailable:'Цена товара уточняется. Уберите его из заказа.',product_missing:'Один из товаров больше недоступен. Обновите корзину.',request_conflict:'Данные заказа изменились. Обновите страницу.'};
form.onsubmit=async e=>{e.preventDefault();if(button.disabled||!validCart.length)return;const phone=form.elements.phone.value.trim();if(!/^[78]\d{10}$/.test(phone.replace(/\D/g,''))){form.elements.phone.setCustomValidity(errors.invalid_input);form.elements.phone.reportValidity();return}button.disabled=true;message.textContent='Отправляем заказ…';
const payload={name:form.elements.name.value.trim(),phone,email:form.elements.email.value.trim(),delivery:form.elements.delivery.value,address:form.elements.address.value.trim(),comment:form.elements.comment.value.trim(),items:validCart};const signature=JSON.stringify(payload);
if(!pending||pending.signature!==signature){pending={signature,key:Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('')};try{sessionStorage.setItem('ps-order-pending',JSON.stringify(pending))}catch(e){}}
try{const j=await request('api/order-create.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,request_key:pending.key})});try{localStorage.removeItem('ps-cart');sessionStorage.removeItem('ps-order-pending')}catch(e){}form.hidden=true;summary.hidden=true;message.textContent='';document.getElementById('done').innerHTML=`<h2>Заказ ${esc(j.order_number)} принят</h2><p>Сумма товаров: <b>${rub(j.total_rub)}</b>.</p><p>Менеджер свяжется с вами для подтверждения наличия, оплаты и получения.</p><a class="primary" href="index.html">Вернуться в магазин</a>`}catch(err){button.disabled=false;message.textContent=errors[err.message]||'Не удалось получить подтверждение. Нажмите ещё раз: повторная отправка того же заказа не создаст дубликат.'}
};
})();
