/* Ownership passport: model photo, maintenance facts and personal replacement cycles. */
function equipmentCareEscape(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function equipmentCareUnit(unit){return ({km:'км',hours:'ч',ski_days:'дней катания'})[unit]||unit;}
function equipmentCareMarkup(vehicle){
  const care=vehicle.passport?.care;if(!care)return '';
  const esc=equipmentCareEscape,unit=equipmentCareUnit(care.usage_unit),labels={unknown:'Нужна проверка',good:'По последней проверке — в порядке',watch:'Требует внимания',soon:'Скоро обслуживание',due:'Нужен сервис'};
  const items=care.items||[];
  return '<section class="equipmentCare"><h4>Расходники и обслуживание</h4><p>Записывайте пробег и обслуживание, чтобы следить за состоянием расходников.</p><form class="equipmentUsageForm"><label>Общий '+(care.usage_unit==='km'?'пробег':'счётчик катания')+', '+esc(unit)+'<input name="usage_value" type="number" min="'+(care.usage_value??0)+'" max="10000000" step="'+(care.usage_unit==='ski_days'?'1':'0.1')+'" value="'+(care.usage_value??'')+'" required></label><button type="submit">Сохранить счётчик</button></form><div class="equipmentCareItems">'+items.map(item=>{
    const known=item.wear_percent!==null&&item.wear_percent!==undefined,pct=known?Math.max(0,Math.min(100,Number(item.wear_percent))):null;
    const history=(item.history||[]).map(e=>'<li>'+esc(new Date(String(e.created_at).replace(' ','T')).toLocaleDateString('ru-RU'))+' · '+esc(({checked:'Осмотр',serviced:'Обслуживание',replaced:'Замена'})[e.event_type]||e.event_type)+(e.usage_value!==null?' · '+esc(e.usage_value)+' '+esc(unit):'')+(Number(e.include_learning)===0?' · аварийная замена':'')+(e.note?' — '+esc(e.note):'')+'</li>').join('');
    return '<article class="equipmentCareItem" data-care-item="'+esc(item.key)+'" data-state="'+esc(item.state)+'"><div class="equipmentCareItemHead"><b>'+esc(item.label)+'</b><span>'+esc(labels[item.state]||labels.unknown)+'</span></div>'+(known?'<label class="equipmentResource">'+(item.basis==='measurement'?'Износ по замеру: ':'Ориентировочный износ: ')+''+pct.toLocaleString('ru-RU',{maximumFractionDigits:1})+'%<progress max="100" value="'+pct+'"></progress></label>'+(item.remaining!==null?'<p>Ориентировочный остаток: '+esc(item.remaining)+' '+esc(unit)+'.</p>':''):'<p class="equipmentResourceUnknown">Ресурс определяется по состоянию.</p>')+'<p>'+esc(item.criterion)+'</p><small>'+esc(item.routine)+'</small>'+(item.interval?'<p>Интервал проверки: '+Number(item.interval)+' '+esc(equipmentCareUnit(item.interval_unit))+(item.service_remaining!==null?' · осталось '+esc(item.service_remaining):' · запишите последнее обслуживание')+'.</p>':'')+(item.source_url?'<a href="'+esc(item.source_url)+'" target="_blank" rel="noopener noreferrer">Рекомендации производителя</a>':'<small>Проверка состояния · рекомендации мастерской</small>')+'<details><summary>Записать проверку или обслуживание</summary><form class="equipmentCareForm" data-care-key="'+esc(item.key)+'"><label>Событие<select name="event_type"><option value="checked">Проверил состояние</option><option value="serviced">Выполнил обслуживание</option><option value="replaced">Заменил расходник</option></select></label><label>Состояние после события<select name="condition_state"><option value="good">В порядке</option><option value="watch">Есть признаки износа</option><option value="due">Нужен сервис</option></select></label>'+(item.measurement_threshold?'<label>Удлинение цепи, '+esc(item.measurement_unit)+'<input name="measurement_value" type="number" min="0" max="100" step="0.01"></label>':'')+'<label>Комментарий<input name="note" maxlength="500" placeholder="Что проверили или заменили"></label><label class="equipmentCareCheckbox"><input type="checkbox" name="exclude_learning"> Замена из-за повреждения</label><button type="submit">Сохранить событие</button></form></details>'+(history?'<details><summary>История ('+(item.history||[]).length+')</summary><ol>'+history+'</ol></details>':'')+'</article>';
  }).join('')+'</div><p class="equipmentCareMessage" role="status" aria-live="polite"></p></section>';
}
function bindEquipmentCare(vehicle,box){
  box.querySelectorAll('.equipmentUsageForm,.equipmentCareForm').forEach(form=>form.onsubmit=async event=>{
    event.preventDefault();const button=form.querySelector('button[type="submit"]'),message=box.querySelector('.equipmentCareMessage');
    const data=Object.fromEntries(new FormData(form));data.vehicle_id=Number(vehicle.id);
    if(form.dataset.careKey){data.care_key=form.dataset.careKey;data.exclude_learning=!!form.elements.exclude_learning.checked;if(form.elements.measurement_value)data.measurement_value=form.elements.measurement_value.value!==''?Number(form.elements.measurement_value.value):null;}
    const usage=box.querySelector('.equipmentUsageForm input');data.usage_value=usage.value!==''?Number(usage.value):null;
    if(!form.dataset.careKey&&data.usage_value===null)return;
    button.disabled=true;message.textContent='Сохраняю…';
    try{await api('equipment_care',{method:'POST',body:JSON.stringify(data)});await refresh(false);const updated=vehicleState.find(v=>String(v.id)===String(vehicle.id));if(updated)openVehiclePassport(updated);}
    catch(error){button.disabled=false;message.textContent=error.message==='bad_usage'?'Счётчик должен быть не меньше предыдущего значения.':'Не удалось сохранить. Проверьте соединение и повторите.';}
  });
}

function equipmentCareServiceOptions(type){const specific=({bicycle:['Тормоза','Передачи и цепь','Колёса и покрышки','Подвеска'],scooter:['Тормоза','Колёса и подшипники','Руль и крепления'],inline_skates:['Колёса и подшипники','Тормоз роликов','Рама и застёжки'],skateboard:['Колёса и подшипники','Дека и подвески'],skis:['Подготовка лыж','Проверка креплений'],snowboard:['Подготовка сноуборда','Проверка креплений']})[type]||[];return ['Диагностика',...specific,'Техническое обслуживание','Другое'];}
