(()=>{
const rub2=n=>new Intl.NumberFormat('ru-RU').format(n||0)+' ₽';
const esc2=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const readArray=k=>{try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch(e){return[]}};
const ruMap={'q':'й','w':'ц','e':'у','r':'к','t':'е','y':'н','u':'г','i':'ш','o':'щ','p':'з','[':'х',']':'ъ','a':'ф','s':'ы','d':'в','f':'а','g':'п','h':'р','j':'о','k':'л','l':'д',';':'ж',"'":'э','z':'я','x':'ч','c':'с','v':'м','b':'и','n':'т','m':'ь',',':'б','.':'ю'};
const enMap=Object.fromEntries(Object.entries(ruMap).map(([a,b])=>[b,a]));
const swap=(s,map)=>[...String(s||'').toLowerCase()].map(ch=>map[ch]||ch).join('');
const synonyms=[[/велик[а-я]*/g,'велосип'],[/^вел$/g,'велосип'],[/\bmtb\b/g,'велосип'],[/горник[а-я]*/g,'горн'],[/запчасти?/g,'запчаст'],[/аксессуары?/g,'аксессуар'],[/лыжи?/g,'лыж'],[/сноуборды?/g,'сноуборд']];
const plain=s=>String(s||'').toLowerCase().trim().replace(/ё/g,'е').replace(/[.,;:()[\]{}"']/g,' ').replace(/\s+/g,' ');
const repairLegacyQuery=s=>plain(s).replace(/^велосипедосипед(?=\s|$)/,'велосипед').replace(/^велосипосипед(?=\s|$)/,'велосипед');
const canon=s=>{let x=repairLegacyQuery(s);for(const [r,v] of synonyms)x=x.replace(r,v);return x.replace(/\s+/g,' ')};
const variants=q=>[canon(q),canon(swap(q,ruMap)),canon(swap(q,enMap))].filter((v,i,a)=>v&&a.indexOf(v)===i);
function ptext(p){return canon([p.name,p.brand,p.model,p.cat,p.pathText,p.description,Object.entries(p.specs||{}).flat().join(' ')].join(' '))}

const accessoryWords=/\b(чехол|сумк|багажник|крыл|фонар|звонок|замок|покрыш|камер|насос|держател|креплен|корзин|зеркал|седл|сиден|педал|грипс|трос|цеп|кассет|звезд|переключ|тормоз|обод|вилк|рам|втулк|спиц|подножк|подстав|крепеж|адаптер|палк|ботинк|маск|очк|перчат|защит|колес|подшип|ось|амортиз|ремкомплект|запчаст)\w*/;
const intentRules=[
 {id:'bicycle',q:/^(?:электро)?велосип/,direct:[/^(?:(?:детск\w*|подростков\w*|горн\w*|складн\w*|городск\w*|дорожн\w*|женск\w*|мужск\w*|трехколесн\w*|3[- ]?х\s*колесн\w*)\s+)*(?:электро\s*)?велосипед\w*(?:\s|$)/,/^электровелосипед\w*(?:\s|$)/]},
 {id:'scooter',q:/^(?:электро)?самокат/,direct:[/^(?:(?:детск\w*|трюков\w*|городск\w*|складн\w*|взросл\w*|двухколесн\w*|трехколесн\w*)\s+)*(?:электро\s*)?самокат\w*(?:\s|$)/,/^электросамокат\w*(?:\s|$)/]},
 {id:'skis',q:/^лыж/,direct:[/^лыж(?:и|а)?\b/,/^(?:(?:горн\w*|бегов\w*|детск\w*|охотнич\w*|туристич\w*|прогулочн\w*)\s+){1,2}лыж(?:и|а)?\b/]},
 {id:'snowboard',q:/^сноуборд/,direct:[/^(?:(?:детск\w*|женск\w*|мужск\w*|унисекс\w*)\s+)*сноуборд\w*(?:\s|$)/]},
 {id:'skates',q:/^коньк/,direct:[/^(?:(?:фигурн\w*|хоккейн\w*|детск\w*|женск\w*|мужск\w*|раздвижн\w*)\s+)*коньк\w*(?:\s|$)/]},
 {id:'rollers',q:/^(?:ролик|роликов)/,direct:[/^(?:(?:детск\w*|женск\w*|мужск\w*|раздвижн\w*)\s+)*(?:роликов\w*\s+коньк\w*|ролик\w*)(?:\s|$)/]},
 {id:'skateboard',q:/^скейтборд/,direct:[/^(?:(?:детск\w*|трюков\w*)\s+)*скейтборд\w*(?:\s|$)/]},
 {id:'longboard',q:/^лонгборд/,direct:[/^лонгборд\w*(?:\s|$)/]},
 {id:'sled',q:/^санк/,direct:[/^санк\w*(?:\s|$)/]},
 {id:'snow_scooter',q:/^снегокат/,direct:[/^снегокат\w*(?:\s|$)/]},
 {id:'tubing',q:/^тюбинг/,direct:[/^тюбинг\w*(?:\s|$)/]},
 {id:'helmet',q:/^шлем/,direct:[/^(?:(?:велосипедн\w*|горнолыжн\w*|хоккейн\w*|детск\w*)\s+)*шлем\w*(?:\s|$)/]},
 {id:'backpack',q:/^рюкзак/,direct:[/^рюкзак\w*(?:\s|$)/]},
 {id:'tent',q:/^палатк/,direct:[/^палатк\w*(?:\s|$)/]},
 {id:'sleeping_bag',q:/^(?:спальник|спальн\w*\s+мешок)/,direct:[/^(?:спальник\w*|спальн\w*\s+мешок\w*)(?:\s|$)/]},
 {id:'trampoline',q:/^батут/,direct:[/^батут\w*(?:\s|$)/]},
 {id:'treadmill',q:/^бегов\w*\s+дорожк/,direct:[/^бегов\w*\s+дорожк\w*(?:\s|$)/]},
 {id:'exercise_bike',q:/^велотренажер/,direct:[/^велотренажер\w*(?:\s|$)/]},
 {id:'elliptical',q:/^(?:эллипс|эллиптическ)/,direct:[/^(?:эллипс\w*|эллиптическ\w*\s+тренажер\w*)(?:\s|$)/]},
 {id:'dumbbell',q:/^гантел/,direct:[/^гантел\w*(?:\s|$)/]},
 {id:'barbell',q:/^штанг/,direct:[/^штанг\w*(?:\s|$)/]},
 {id:'kettlebell',q:/^гир(?:я|и|ь)/,direct:[/^гир(?:я|и|ь)\w*(?:\s|$)/]},
 {id:'racket',q:/^ракетк/,direct:[/^ракетк\w*(?:\s|$)/]},
 {id:'ball',q:/^мяч/,direct:[/^мяч\w*(?:\s|$)/]},
 {id:'hockey_stick',q:/^клюшк/,direct:[/^клюшк\w*(?:\s|$)/]},
 {id:'pool',q:/^бассейн/,direct:[/^бассейн\w*(?:\s|$)/]},
 {id:'sup',q:/^(?:сап|sup)(?:\s|$)/,direct:[/^(?:сап|sup)(?:[- ]?борд\w*)?(?:\s|$)/]},
 {id:'kayak',q:/^каяк/,direct:[/^каяк\w*(?:\s|$)/]},
 {id:'boat',q:/^лодк/,direct:[/^лодк\w*(?:\s|$)/]}
];
function searchIntent(q){const c=canon(q);if(!c)return'';for(const r of intentRules){if(!r.q.test(c))continue;if(accessoryWords.test(c)&&!['helmet','backpack'].includes(r.id))return'';return r.id}return''}
function intentRule(id){return intentRules.find(r=>r.id===id)}
function isPrimaryProduct(p,intent){if(!intent)return true;const rule=intentRule(intent);if(!rule)return true;const n=plain(p.name||'');return rule.direct.some(r=>r.test(n))}
function matchesIntent(p,intent){return !intent||isPrimaryProduct(p,intent)}
function relevanceScore(p,q,intent){const c=canon(q),n=canon(p.name||''),brand=canon(p.brand||''),model=canon(p.model||''),cat=canon(p.cat||''),path=canon(p.pathText||'');let s=0;if(intent&&isPrimaryProduct(p,intent))s+=1200;if(n===c)s+=1000;if(n.startsWith(c))s+=650;else if(n.includes(c))s+=420;if(brand===c||model===c)s+=500;else if(brand.startsWith(c)||model.startsWith(c))s+=280;if(cat.includes(c))s+=120;if(path.includes(c))s+=80;const pos=n.indexOf(c);if(pos>0){const prefix=n.slice(0,pos);if(accessoryWords.test(prefix)||/(?:для|на|под|к)\s*$/.test(prefix.trim()))s-=500}return s}
function bestQuery(q){const vs=variants(q);if(!vs.length)return'';for(const v of vs){const intent=searchIntent(v);if(products.some(p=>matchesIntent(p,intent)&&ptext(p).includes(v)))return v}return vs[0]}
function imageOf(p){return p.image||((p.images||[])[0])||''}
function waitProducts(cb){let n=0;const t=setInterval(()=>{n++;if(typeof products!=='undefined'&&products.length){clearInterval(t);cb()}else if(n>100)clearInterval(t)},100)}

function buildMega(){const nav=document.querySelector('body>nav');if(!nav)return;const groups=new Map();for(const p of products){const path=Array.isArray(p.path)?p.path.filter(Boolean):[];const top=path[0]||p.cat||'Каталог';const sub=path[1]||p.cat||'';if(!groups.has(top))groups.set(top,new Map());if(sub)groups.get(top).set(sub,(groups.get(top).get(sub)||0)+1)}const ranked=[...groups.entries()].sort((a,b)=>[...b[1].values()].reduce((x,y)=>x+y,0)-[...a[1].values()].reduce((x,y)=>x+y,0)).slice(0,9);const panel=document.createElement('div');panel.className='megaCatalog';panel.id='megaCatalog';panel.innerHTML=ranked.map(([top,subs])=>`<section class="megaGroup"><h3>${esc2(top)}</h3>${[...subs.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([s,c])=>`<a href="#catalogProducts" data-mega-term="${esc2(s)}">${esc2(s)} <small>(${c})</small></a>`).join('')}</section>`).join('')+`<a class="megaAll" href="#catalogProducts" data-mega-all>Весь каталог →</a>`;const back=document.createElement('div');back.className='megaCatalogBackdrop';document.body.append(back,panel);const catalogLink=[...nav.querySelectorAll('a')].find(a=>a.textContent.trim()==='Каталог');const close=()=>{panel.classList.remove('open');back.classList.remove('open')};const open=()=>{panel.classList.add('open');back.classList.add('open')};if(catalogLink){catalogLink.addEventListener('click',e=>{e.preventDefault();panel.classList.contains('open')?close():open()})}back.onclick=close;panel.querySelectorAll('[data-mega-term]').forEach(a=>a.onclick=e=>{e.preventDefault();const term=a.dataset.megaTerm||'';if(document.querySelector('#q'))q.value=term;if(document.querySelector('#mobileQ'))mobileQ.value=term;category.value='';apply();close();document.querySelector('#catalogProducts')?.scrollIntoView({behavior:'smooth'})});panel.querySelector('[data-mega-all]').onclick=()=>{if(document.querySelector('#q'))q.value='';if(document.querySelector('#mobileQ'))mobileQ.value='';category.value='';apply();close()}}

function buildSuggestions(input,form){if(!input||!form)return;let wrap=form.parentElement;if(!wrap.classList.contains('smartSearchWrap')){wrap=document.createElement('div');wrap.className='smartSearchWrap';form.parentNode.insertBefore(wrap,form);wrap.appendChild(form)}let box=wrap.querySelector('.smartSuggest');if(!box){box=document.createElement('div');box.className='smartSuggest';wrap.appendChild(box)}const render=()=>{const raw=input.value.trim();if(raw.length<2){box.classList.remove('open');box.innerHTML='';return}const qv=bestQuery(raw),terms=qv.split(' ').filter(Boolean),intent=searchIntent(qv||raw);const found=products.map(p=>({p,txt:ptext(p)})).filter(x=>matchesIntent(x.p,intent)&&terms.every(t=>x.txt.includes(t))).sort((a,b)=>relevanceScore(b.p,qv,intent)-relevanceScore(a.p,qv,intent)).slice(0,7);if(!found.length){box.innerHTML='<a href="#catalogProducts"><span class="suggestPh"></span><span><b>Ничего точного не найдено</b><small>Показать результаты поиска</small></span><strong>→</strong></a>';box.classList.add('open');return}box.innerHTML=found.map(({p})=>`<a href="product.html?id=${encodeURIComponent(p.id)}">${imageOf(p)?`<img src="${esc2(imageOf(p))}" alt="">`:'<span class="suggestPh"></span>'}<span><b>${esc2(p.name)}</b><small>${esc2([p.brand,p.cat].filter(Boolean).join(' · '))}</small></span><strong>${rub2(p.price)}</strong></a>`).join('');box.classList.add('open')};input.addEventListener('input',render);input.addEventListener('focus',render);document.addEventListener('click',e=>{if(!wrap.contains(e.target))box.classList.remove('open')});const old=form.onsubmit;form.onsubmit=e=>{if(input.id==='q'&&document.querySelector('#mobileQ'))mobileQ.value=input.value;if(input.id==='mobileQ'&&document.querySelector('#q'))q.value=input.value;box.classList.remove('open');if(typeof old==='function')return old.call(form,e)}}

function installFilters(){const filters=document.querySelector('.filters');if(!filters||document.querySelector('#brandFilter'))return;const row=document.createElement('div');row.className='kantFilterRow';const brand=document.createElement('select');brand.id='brandFilter';brand.innerHTML='<option value="">Все бренды</option>'+[...new Set(products.map(p=>p.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru')).map(b=>`<option>${esc2(b)}</option>`).join('');const stock=document.createElement('label');stock.className='stockOnly';stock.innerHTML='<input type="checkbox" id="stockOnly"> Только в наличии';row.append(brand,stock);filters.after(row);apply=function(resetPage=true){let list=[...products],c=category.value,min=+minPrice.value||0,max=+maxPrice.value||Infinity,qraw=(document.querySelector('#q')?.value||document.querySelector('#mobileQ')?.value||'').trim(),qv=bestQuery(qraw),intent=searchIntent(qv||qraw);if(c)list=list.filter(p=>p.cat===c);if(qv){const ts=qv.split(' ').filter(Boolean);list=list.filter(p=>matchesIntent(p,intent)&&ts.every(t=>ptext(p).includes(t)));if(sort.value==='popular')list.sort((a,b)=>relevanceScore(b,qv,intent)-relevanceScore(a,qv,intent))}if(brand.value)list=list.filter(p=>p.brand===brand.value);if(stock.querySelector('input').checked)list=list.filter(p=>p.stockCode==='in');list=list.filter(p=>p.price>=min&&p.price<=max);if(sort.value==='priceAsc')list.sort((a,b)=>a.price-b.price);if(sort.value==='priceDesc')list.sort((a,b)=>b.price-a.price);if(sort.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'ru'));if(resetPage)page=1;render(list)};brand.onchange=()=>apply();stock.onchange=()=>apply();const oldReset=resetFilters.onclick;resetFilters.onclick=e=>{brand.value='';stock.querySelector('input').checked=false;oldReset&&oldReset.call(resetFilters,e)}}

async function installFavorites(){let fav=readArray('ps-favorites').map(String),csrf='',logged=false;try{const r=await fetch('api/customer.php?action=me',{cache:'no-store'}),j=await r.json();if(r.ok&&j.ok&&j.customer){csrf=j.csrf||'';logged=true;fav=(j.favorites||[]).map(String);localStorage.setItem('ps-favorites',JSON.stringify(fav))}}catch(e){}const oldRender=render;render=function(list=view){oldRender(list);document.querySelectorAll('.product').forEach(card=>{const link=card.querySelector('a[href*="product.html?id="]');if(!link)return;const id=new URL(link.href).searchParams.get('id');if(!id)return;const p=products.find(x=>String(x.id)===String(id));if(p?.oldPrice&&p.oldPrice>p.price){const price=card.querySelector('.price');if(price&&!card.querySelector('.productDiscount')){const pct=Math.round((1-p.price/p.oldPrice)*100);price.insertAdjacentHTML('afterend',`<span class="productDiscount">−${pct}%</span>`)}}const b=document.createElement('button');b.type='button';b.className='productFavorite'+(fav.includes(String(id))?' active':'');b.setAttribute('aria-label','В избранное');b.textContent=fav.includes(String(id))?'♥':'♡';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const s=String(id);if(logged){try{const r=await fetch('api/customer.php?action=favorite',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({product_id:Number(id)})}),j=await r.json();if(!r.ok||!j.ok)throw 0;if(j.active&&!fav.includes(s))fav.push(s);if(!j.active)fav=fav.filter(x=>x!==s)}catch(err){location.href='profile.html';return}}else{const i=fav.indexOf(s);if(i>=0)fav.splice(i,1);else fav.push(s)}localStorage.setItem('ps-favorites',JSON.stringify(fav));b.classList.toggle('active',fav.includes(s));b.textContent=fav.includes(s)?'♥':'♡'};card.appendChild(b)})};render(view)}

waitProducts(()=>{const desk=document.querySelector('#q'),mob=document.querySelector('#mobileQ');const current=(desk?.value||mob?.value||'').trim();const repaired=repairLegacyQuery(current);if(current&&repaired!==plain(current)){if(desk)desk.value=repaired;if(mob)mob.value=repaired}buildMega();buildSuggestions(desk,document.querySelector('#search'));buildSuggestions(mob,document.querySelector('#mobileSearch'));installFilters();apply(false);installFavorites()});
})();