/* Decorative subsection artwork, scoped by section; product photos remain independent. */
const SUBCATEGORY_ART={
  "bicycle": {
    "детские": "assets/categories/subsections/bicycle-01-v1.webp",
    "горные 27,5\"": "assets/categories/subsections/bicycle-02-v1.webp",
    "горные 29\"": "assets/categories/subsections/bicycle-03-v1.webp",
    "детские спортивные 20\"": "assets/categories/subsections/bicycle-04-v1.webp",
    "подростковые 24\"": "assets/categories/subsections/bicycle-05-v1.webp",
    "малышам": "assets/categories/subsections/bicycle-06-v1.webp",
    "горные 26\"": "assets/categories/subsections/bicycle-07-v1.webp",
    "bmx (экстрим)": "assets/categories/subsections/bicycle-08-v1.webp",
    "дорожные и городские": "assets/categories/subsections/bicycle-09-v1.webp",
    "горные женские": "assets/categories/subsections/bicycle-10-v1.webp",
    "беговелы": "assets/categories/subsections/bicycle-11-v1.webp",
    "складные": "assets/categories/subsections/bicycle-12-v1.webp",
    "фэтбайки": "assets/categories/subsections/bicycle-13-v1.webp",
    "шоссе": "assets/categories/subsections/bicycle-14-v1.webp",
    "двухподвесы": "assets/categories/subsections/bicycle-15-v1.webp",
    "гибриды": "assets/categories/subsections/bicycle-16-v1.webp"
  },
  "cycling": {
    "для комплекта": "assets/categories/subsections/ebike-kit-v1.webp",
    "на подростковые и взрослые велосипеды": "assets/categories/subsections/cycling-01-v1.webp",
    "камеры": "assets/categories/subsections/cycling-02-v1.webp",
    "спицы": "assets/categories/subsections/cycling-03-v1.webp",
    "колеса": "assets/categories/subsections/cycling-04-v1.webp",
    "втулки": "assets/categories/subsections/cycling-05-v1.webp",
    "грипсы": "assets/categories/subsections/cycling-06-v1.webp",
    "тормозные колодки": "assets/categories/subsections/cycling-07-v1.webp",
    "каретки": "assets/categories/subsections/cycling-08-v1.webp",
    "звезды": "assets/categories/subsections/cycling-09-v1.webp",
    "переключатели": "assets/categories/subsections/cycling-10-v1.webp",
    "шатуны": "assets/categories/subsections/cycling-11-v1.webp",
    "на детские велосипеды и bmx": "assets/categories/subsections/cycling-12-v1.webp",
    "вилки и амортизация": "assets/categories/subsections/cycling-13-v1.webp",
    "подшипники": "assets/categories/subsections/cycling-14-v1.webp",
    "манетки": "assets/categories/subsections/cycling-15-v1.webp",
    "запчасти для bmx": "assets/categories/subsections/cycling-16-v1.webp",
    "седла": "assets/categories/subsections/cycling-17-v1.webp",
    "подседельные штыри": "assets/categories/subsections/cycling-18-v1.webp",
    "тросики, рубашки": "assets/categories/subsections/cycling-19-v1.webp",
    "выносы": "assets/categories/subsections/cycling-20-v1.webp",
    "обода": "assets/categories/subsections/cycling-21-v1.webp",
    "педали": "assets/categories/subsections/cycling-22-v1.webp",
    "цепи": "assets/categories/subsections/cycling-23-v1.webp",
    "рулевые колонки": "assets/categories/subsections/cycling-24-v1.webp",
    "рули": "assets/categories/subsections/cycling-25-v1.webp",
    "детали для вилки": "assets/categories/subsections/cycling-26-v1.webp",
    "тормозные ротора (диски)": "assets/categories/subsections/cycling-27-v1.webp",
    "хомуты, эксцентрики": "assets/categories/subsections/cycling-28-v1.webp",
    "тормоза гидравлические": "assets/categories/subsections/cycling-29-v1.webp",
    "на детские коляски": "assets/categories/subsections/cycling-30-v1.webp",
    "адаптеры": "assets/categories/subsections/cycling-31-v1.webp",
    "запчасти для рам": "assets/categories/subsections/cycling-32-v1.webp",
    "рога": "assets/categories/subsections/cycling-33-v1.webp",
    "на садовые тачки": "assets/categories/subsections/cycling-34-v1.webp",
    "тормоза v-brake": "assets/categories/subsections/cycling-35-v1.webp",
    "ремонт камер": "assets/categories/subsections/cycling-36-v1.webp",
    "калиперы": "assets/categories/subsections/cycling-37-v1.webp",
    "тормозные ручки": "assets/categories/subsections/cycling-38-v1.webp",
    "на фэтбайки": "assets/categories/subsections/cycling-39-v1.webp",
    "запчасти": "assets/categories/subsections/cycling-40-v1.webp",
    "на инвалидные коляски": "assets/categories/subsections/cycling-41-v1.webp",
    "рамы": "assets/categories/subsections/cycling-42-v1.webp",
    "чехлы для велосипедов": "assets/categories/subsections/cycling-43-v1.webp"
  },
  "accessories": {
    "спортивные аксессуары": "assets/categories/subsections/sports-accessories-v1.webp",
    "инструменты": "assets/categories/subsections/accessories-01-v1.webp",
    "сигналы": "assets/categories/subsections/accessories-02-v1.webp",
    "световое оборудование": "assets/categories/subsections/accessories-03-v1.webp",
    "багажники, корзины": "assets/categories/subsections/accessories-04-v1.webp",
    "крылья": "assets/categories/subsections/accessories-05-v1.webp",
    "флипперы, колпачки, нипеля": "assets/categories/subsections/accessories-06-v1.webp",
    "велосумки, бордачки": "assets/categories/subsections/accessories-07-v1.webp",
    "шлемы": "assets/categories/subsections/accessories-08-v1.webp",
    "смазки и очистители": "assets/categories/subsections/accessories-09-v1.webp",
    "подножки": "assets/categories/subsections/accessories-10-v1.webp",
    "противоугонные системы": "assets/categories/subsections/accessories-11-v1.webp",
    "флягодержатели": "assets/categories/subsections/accessories-12-v1.webp",
    "отражатели, наклейки, украшения": "assets/categories/subsections/accessories-13-v1.webp",
    "защиты": "assets/categories/subsections/accessories-14-v1.webp",
    "фляги и питьевые системы": "assets/categories/subsections/accessories-15-v1.webp",
    "велоперчатки": "assets/categories/subsections/accessories-16-v1.webp",
    "насосы": "assets/categories/subsections/accessories-17-v1.webp",
    "зеркала": "assets/categories/subsections/accessories-18-v1.webp",
    "аксессуары": "assets/categories/subsections/accessories-19-v1.webp",
    "тормозные аксессуары": "assets/categories/subsections/accessories-20-v1.webp",
    "платки, повязки, банданы": "assets/categories/subsections/accessories-21-v1.webp",
    "детские велокресла": "assets/categories/subsections/accessories-22-v1.webp",
    "носки, гетры": "assets/categories/subsections/accessories-23-v1.webp",
    "разное": "assets/categories/subsections/accessories-24-v1.webp",
    "пеги и хабгарды": "assets/categories/subsections/accessories-25-v1.webp",
    "крепления": "assets/categories/subsections/accessories-26-v1.webp",
    "опорные колесики": "assets/categories/subsections/accessories-27-v1.webp",
    "очки": "assets/categories/subsections/accessories-28-v1.webp",
    "велокомпьютеры": "assets/categories/subsections/accessories-29-v1.webp",
    "стойки для ремонта и хранения": "assets/categories/subsections/accessories-30-v1.webp",
    "велобагажники (велокрепления) для автомобиля": "assets/categories/subsections/accessories-31-v1.webp",
    "термобелье": "assets/categories/subsections/accessories-32-v1.webp",
    "лосины": "assets/categories/subsections/accessories-33-v1.webp",
    "поддерживающие ручки": "assets/categories/subsections/accessories-34-v1.webp",
    "велоприцепы": "assets/categories/subsections/accessories-35-v1.webp",
    "аксессуары для надувной продукциии": "assets/categories/subsections/accessories-36-v1.webp",
    "майки": "assets/categories/subsections/accessories-37-v1.webp"
  },
  "fitness": {
    "эспандеры": "assets/categories/subsections/fitness-01-v1.webp",
    "железо": "assets/categories/subsections/fitness-02-v1.webp",
    "аксессуары для тренировок": "assets/categories/subsections/fitness-03-v1.webp",
    "лапы": "assets/categories/subsections/fitness-04-v1.webp",
    "мячи для фитнеса": "assets/categories/subsections/fitness-05-v1.webp",
    "скакалки": "assets/categories/subsections/fitness-06-v1.webp",
    "футбольные мячи": "assets/categories/subsections/fitness-07-v1.webp",
    "баскетбол": "assets/categories/subsections/fitness-08-v1.webp",
    "мешки и груши, крепеж": "assets/categories/subsections/fitness-09-v1.webp",
    "брусья": "assets/categories/subsections/fitness-10-v1.webp",
    "волейбольные мячи и аксессуары": "assets/categories/subsections/fitness-11-v1.webp",
    "коврики для фитнеса": "assets/categories/subsections/fitness-12-v1.webp",
    "тренажеры": "assets/categories/subsections/fitness-13-v1.webp",
    "капы": "assets/categories/subsections/fitness-14-v1.webp",
    "бинты": "assets/categories/subsections/fitness-15-v1.webp",
    "обручи": "assets/categories/subsections/fitness-16-v1.webp",
    "аксессуары для единоборств": "assets/categories/subsections/fitness-17-v1.webp",
    "шлемы для единоборств": "assets/categories/subsections/fitness-18-v1.webp",
    "теннисные аксессуары": "assets/categories/subsections/fitness-19-v1.webp",
    "утяжелители": "assets/categories/subsections/fitness-20-v1.webp",
    "суппорта": "assets/categories/subsections/fitness-21-v1.webp",
    "спортивные бутылки и шейкеры": "assets/categories/subsections/fitness-22-v1.webp",
    "разное": "assets/categories/subsections/fitness-23-v1.webp",
    "фитнес и тренажеры": "assets/categories/subsections/fitness-24-v1.webp",
    "карате": "assets/categories/subsections/fitness-25-v1.webp",
    "аксессуары для футбола": "assets/categories/subsections/fitness-26-v1.webp",
    "игровые виды спорта, прочее": "assets/categories/subsections/fitness-27-v1.webp",
    "бейсбол": "assets/categories/subsections/fitness-28-v1.webp",
    "велотренажеры": "assets/categories/subsections/fitness-29-v1.webp",
    "маты": "assets/categories/subsections/fitness-30-v1.webp",
    "пульсометры": "assets/categories/subsections/fitness-31-v1.webp",
    "диски здоровья": "assets/categories/subsections/fitness-32-v1.webp",
    "самбо": "assets/categories/subsections/fitness-33-v1.webp",
    "чешки, балетки": "assets/categories/subsections/fitness-34-v1.webp",
    "волейбольные сетки": "assets/categories/subsections/fitness-35-v1.webp",
    "дзюдо": "assets/categories/subsections/fitness-36-v1.webp",
    "воланы, мячи, сетки, струны": "assets/categories/subsections/fitness-37-v1.webp",
    "дополнительное оборудование": "assets/categories/subsections/fitness-38-v1.webp",
    "большой теннис": "assets/categories/subsections/fitness-39-v1.webp",
    "перчатки": "assets/categories/subsections/fitness-40-v1.webp",
    "упоры для отжиманий": "assets/categories/subsections/fitness-41-v1.webp",
    "оборудование для фитнеса": "assets/categories/subsections/fitness-42-v1.webp",
    "настольные игры": "assets/categories/subsections/fitness-43-v1.webp",
    "детские спортивные комплексы": "assets/categories/subsections/fitness-44-v1.webp",
    "столы для настольного тенниса": "assets/categories/subsections/fitness-45-v1.webp",
    "игровой спорт": "assets/categories/subsections/fitness-46-v1.webp",
    "перчатки для фитнеса": "assets/categories/subsections/fitness-47-v1.webp",
    "сетки для настольного тенниса": "assets/categories/subsections/fitness-48-v1.webp",
    "дартс": "assets/categories/subsections/fitness-49-v1.webp",
    "футбольные сетки": "assets/categories/subsections/fitness-50-v1.webp"
  },
  "service": {
    "диагностика": "assets/categories/subsections/service-01-v1.webp",
    "тормоза": "assets/categories/subsections/service-02-v1.webp",
    "передачи и цепь": "assets/categories/subsections/service-03-v1.webp",
    "колеса и покрышки": "assets/categories/subsections/service-04-v1.webp",
    "техническое обслуживание": "assets/categories/subsections/service-05-v1.webp",
    "сборка и настройка": "assets/categories/subsections/service-06-v1.webp"
  }
};
function subcategoryArtwork(section,title){
  const key=String(title||'').toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ').trim();
  return SUBCATEGORY_ART[section]?.[key]||null;
}
