const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const c=require('../collections.js');global.CMSCollections=c;const components=require('../components.js');
const collection={id:'news',titleField:'title',fields:[{key:'title',type:'string',label:'Title'},{key:'price',type:'number',label:'Price'},{key:'category',type:'string',label:'Category'}],entries:[10,2,null].map((price,i)=>({id:'item-'+i,slug:'item-'+i,status:'published',values:{title:'Record '+i,price,category:'A'}})),template:[{}]};collection.entries.push({id:'secret',slug:'secret',status:'draft',values:{title:'Secret'}});
const recipe={id:'list',type:'collection',collection:'news',props:{title:'List'},mapping:{title:'title',text:'price'},query:{sortField:'price',direction:'asc',filterField:'category',pageSize:2}};
const result=c.render(recipe,[collection]);assert.deepEqual(result.items.map(x=>x.text),['2','10','']);assert.equal(result.items[0].recordPage,'c-4-news-item-1.html');assert(!JSON.stringify(result).includes('Secret'));
const expanded=components.expand(recipe,[],[collection]);assert.equal(expanded.type,'collection-list');assert.deepEqual(components.reference(expanded),recipe);expanded.items[0].title='Accidental canvas change';assert.equal(collection.entries[1].values.title,'Record 1');assert.deepEqual(components.reference(expanded),recipe);
const scope={window:{},location:{href:'https://example.test/'},URL};vm.createContext(scope);vm.runInContext(fs.readFileSync('cms/blocks.js','utf8'),scope);
result.items[0].title='<script>bad</script>';result.items[0].recordPage='javascript:bad';result.filterLabel='" onclick="bad';const html=scope.window.CMBlocks.html(result);assert(!html.includes('<script>'));assert(!html.includes('data-cms-record="javascript:'));assert(html.includes('&lt;script&gt;'));assert(html.includes('data-list-next'));assert(html.includes('hidden'));
console.log('Collection client model passed: typed sorting, record privacy, recipe roundtrip, clone isolation and safe HTML');
