const {chromium}=require('playwright'),assert=require('node:assert/strict');
assert.equal(process.env.CMS_TEST,'1');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chromium'});try{
 const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto('http://localhost:8123/cms/');await page.locator('#loginForm [name=username]').fill('test-owner');await page.locator('#loginForm [name=password]').fill('test-only-password-1234');await page.locator('#loginForm button').click();await page.waitForFunction(()=>typeof canvasMain!=='undefined'&&canvasMain&&!building);
 await page.evaluate(async()=>{const key='collection-ui-'+Date.now();await api('create-site',{key,name:'Collection UI test',url:'https://example.test/'});await switchSite(key);});
 await page.locator('#collectionsButton').click();await page.getByRole('button',{name:'Новая коллекция',exact:true}).click();
 await page.getByLabel('Название коллекции',{exact:true}).fill('Новости');await page.getByLabel('Адрес коллекции',{exact:true}).fill('news');
 await page.getByRole('button',{name:'Добавить поле',exact:true}).click();const extra=page.locator('#collectionSchemaDialog fieldset').nth(1);await extra.getByLabel('Подпись поля',{exact:true}).fill('Стоимость');await extra.getByLabel('Адрес поля',{exact:true}).fill('price');await extra.getByLabel('Тип поля',{exact:true}).selectOption('number');
 await page.getByRole('button',{name:'Сохранить коллекцию',exact:true}).click();await page.waitForFunction(()=>!dirty&&state.draft.collections?.length===1);
 async function newEntry(){await page.locator('#collectionsButton').click();await page.getByRole('button',{name:'Открыть записи',exact:true}).click();await page.getByRole('button',{name:'Добавить запись',exact:true}).click();}
 await newEntry();await page.getByLabel('Адрес записи',{exact:true}).fill('launch');await page.getByLabel('Включение в публикацию').selectOption('published');await page.getByLabel('Стоимость',{exact:true}).fill('0');await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();await page.locator('#collectionEntryDialog [role=status]').filter({hasText:'обязательные поля'}).waitFor();
 assert.equal(await page.evaluate(()=>state.draft.collections[0].entries.length),0);
 await page.locator('#collectionEntryDialog').getByLabel('Название',{exact:true}).fill('Открытие студии');await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();await page.waitForFunction(()=>!dirty&&state.draft.collections[0].entries.length===1);
 await page.reload();await page.waitForFunction(()=>typeof canvasMain!=='undefined'&&canvasMain&&!building);assert.equal(await page.evaluate(()=>state.draft.collections[0].entries[0].values.price),0);
 await newEntry();await page.getByLabel('Адрес записи',{exact:true}).fill('next');await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();await page.waitForFunction(()=>!dirty&&state.draft.collections[0].entries.length===2);
 await page.locator('#collectionsButton').click();await page.getByRole('button',{name:'Открыть записи',exact:true}).click();await page.getByLabel('Поиск записей',{exact:true}).fill('студии');assert.equal(await page.locator('#collectionRecordsDialog .site-card').count(),1);
 if(process.env.CMS_SCREENSHOT_DIR){await page.setViewportSize({width:390,height:844});await page.screenshot({path:process.env.CMS_SCREENSHOT_DIR+'/collections-mobile.png'});await page.setViewportSize({width:1280,height:720});}
 await page.getByRole('button',{name:'Редактировать запись',exact:true}).click();await page.getByLabel('Стоимость',{exact:true}).fill('150');await page.getByRole('button',{name:'Сохранить запись',exact:true}).click();await page.waitForFunction(()=>!dirty&&state.draft.collections[0].entries[0].values.price===150);
 // Validation is read-only and never advances the document revision.
 assert.equal(await page.evaluate(async()=>{const before=state.version;await api('validate-collections',{collections:state.draft.collections});return (await api('state')).version===before;}),true);
 assert.equal(await page.evaluate(async()=>{const response=await fetch('api.php?action=validate-collections&site='+site,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({collections:[]})});return response.status;}),403);
 await page.locator('#collectionsButton').click();await page.getByRole('button',{name:'Шаблон страниц',exact:true}).click();await page.getByRole('button',{name:'Добавить секцию в шаблон',exact:true}).click();await page.getByLabel('Текст — источник',{exact:true}).selectOption('price');await page.getByRole('button',{name:'Предпросмотр шаблона',exact:true}).click();await page.frameLocator('#collectionTemplateDialog iframe').getByRole('heading',{name:'Открытие студии',exact:true}).waitFor();await page.frameLocator('#collectionTemplateDialog iframe').getByText('150',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Сохранить шаблон',exact:true}).click();await page.waitForFunction(()=>!dirty&&state.draft.collections[0].template?.length===1);
 const recordURL=await page.evaluate(()=>collectionPageURL(state.draft.collections[0],state.draft.collections[0].entries[0]));const beforePublish=await context.request.get(recordURL);assert.equal(beforePublish.status(),404,recordURL+' '+(await beforePublish.text()).slice(0,500));
 await page.locator('#publish').click();await page.locator('#confirmPublish').click();await page.waitForFunction(()=>state.published_version>0&&!busy);
 const live=await context.newPage();await live.goto(recordURL);await live.getByRole('heading',{name:'Открытие студии',exact:true}).waitFor();await live.getByText('150',{exact:true}).waitFor();assert.equal(await live.title(),'Открытие студии');
 const draftURL=await page.evaluate(()=>collectionPageURL(state.draft.collections[0],state.draft.collections[0].entries[1]));assert.equal((await context.request.get(draftURL)).status(),404);await live.close();
 // The UI reports referenced-record deletion without losing the current draft.
 await page.evaluate(async()=>{const c=state.draft.collections[0];c.fields.push({key:'source',label:'Источник',type:'reference',target:c.id,required:false});c.entries[1].values.source=c.entries[0].id;changed();await autosave.settle();await mutation('save');});
 await page.locator('#collectionsButton').click();await page.getByRole('button',{name:'Открыть записи',exact:true}).click();await page.getByLabel('Поиск записей',{exact:true}).fill('студии');await page.getByRole('button',{name:'Удалить запись',exact:true}).click();await page.locator('#collectionRecordsDialog [role=status]').filter({hasText:'Запись по ссылке не найдена'}).waitFor();assert.equal(await page.evaluate(()=>state.draft.collections[0].entries.length),2);
 await page.locator('#collectionRecordsDialog').getByRole('button',{name:'Закрыть',exact:true}).click();
 const username='cv-'+Date.now(),password='collection-viewer-test-123';await page.evaluate(async({username,password})=>{await api('create-user',{username,password,memberships:[{site_key:site,role:'viewer'}]});},{username,password});
 const viewer=await browser.newContext(),view=await viewer.newPage();await view.goto('http://localhost:8123/cms/');await view.locator('#loginForm [name=username]').fill(username);await view.locator('#loginForm [name=password]').fill(password);await view.locator('#loginForm button').click();await view.waitForFunction(()=>typeof state!=='undefined'&&state?.role==='viewer');assert.equal(await view.locator('#collectionsButton').isVisible(),false);
 assert.equal(await view.evaluate(async()=>{const r=await fetch('api.php?action=validate-collections&site='+site,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({collections:[]})});return r.status;}),403);await viewer.close();
 assert.deepEqual(errors,[]);console.log('Collection UI passed: schemas, numeric fields, validation errors, publish eligibility, incomplete drafts, reload, search, editing, protected deletion and viewer denial');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
