// Run against a freshly extracted release with a disposable *_test database.
const {chromium}=require('playwright'),assert=require('node:assert/strict');assert.equal(process.env.CMS_TEST,'1');
const base=process.env.CMS_PORTABLE_URL||'http://localhost:8124/';assert(/^http:\/\/localhost:\d+\/$/.test(base));
(async()=>{const browser=await chromium.launch({headless:true,channel:'chromium'});try{
 const context=await browser.newContext(),page=await context.newPage(),errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&/\.(js|css)(?:\?|$)/.test(r.url()))failed.push(r.url());});
 await page.goto(base+'install.php');await page.locator('[name=token]').fill('portable-test-install-token-1234567890');await page.locator('[name=username]').fill('portable-owner');await page.locator('[name=password]').fill('portable-test-password-123');await page.getByRole('button',{name:'Установить',exact:true}).click();await page.getByText('CMS установлена. Удалите install_token из конфигурации.',{exact:true}).waitFor();
 assert.equal((await context.request.get(base+'install.php')).status(),403);await page.getByRole('link',{name:'Войти',exact:true}).click();await page.locator('#loginForm [name=username]').fill('portable-owner');await page.locator('#loginForm [name=password]').fill('portable-test-password-123');await page.locator('#loginForm button').click();await page.waitForFunction(()=>typeof canvasMain!=='undefined'&&canvasMain&&!building);
 assert.equal(await page.evaluate(()=>state.manifest.site),'generic');assert.equal(await page.evaluate(()=>Object.keys(state.manifest.pages).length),0);assert.equal(await page.evaluate(()=>Object.keys(state.templates).length),0);
 await page.locator('#addSectionTop').click();await page.getByRole('button',{name:'Добавить · Текст',exact:true}).click();await page.locator('#closeEditor').click();await page.evaluate(()=>{updateRecipe(sectionModels()[0],'title','Чистая установка ID Studio');});await page.waitForFunction(()=>!dirty);
 await page.locator('#seoButton').click();await page.getByLabel('Описание для поиска',{exact:true}).fill('Независимая установка из архива');await page.getByRole('button',{name:'Сохранить SEO',exact:true}).click();await page.waitForFunction(()=>!dirty);
 await page.locator('#publish').click();await page.locator('#confirmPublish').click();await page.waitForFunction(()=>state.published_version===1&&!busy);const site=await page.evaluate(()=>state.site.key),live=await context.newPage();await live.goto(base+'site.php?site='+site+'&page=index.html');await live.getByRole('heading',{name:'Чистая установка ID Studio',exact:true}).waitFor();assert.equal(await live.locator('meta[name=description]').getAttribute('content'),'Независимая установка из архива');const xml=await (await context.request.get(base+'sitemap.php?site='+site)).text();assert(xml.includes('page=index.html'));
 // Authentication remains independent of the storefront; generic fields mode works.
 await page.goto(base+'fields.html?site='+site);await page.getByText('У этого сайта нет связанных текстовых полей. Страницы редактируются в визуальном редакторе.',{exact:true}).waitFor();assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log('Extracted portable release passed: first install, installation lock, independent login, generic editor, autosave, SEO, publication, sitemap and fields mode');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
