const {chromium}=require('playwright'),assert=require('node:assert/strict');assert.equal(process.env.CMS_TEST,'1');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chromium'});try{
 const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8123/cms/');await page.locator('#loginForm [name=username]').fill('test-owner');await page.locator('#loginForm [name=password]').fill('test-only-password-1234');await page.locator('#loginForm button').click();await page.waitForFunction(()=>typeof canvasMain!=='undefined'&&canvasMain&&!building);
 const site=await page.evaluate(async()=>{const key='seo-'+Date.now();await api('create-site',{key,name:'SEO test',url:'https://example.test/'});await switchSite(key);return key;});
 await page.locator('#seoButton').click();await page.getByLabel('Заголовок для поиска',{exact:true}).fill('Поисковый заголовок <script>');await page.getByLabel('Описание для поиска',{exact:true}).fill('Описание & подробности');await page.getByLabel('Изображение для соцсетей — URL',{exact:true}).fill('/cms/media/share.jpg');await page.getByRole('button',{name:'Сохранить SEO',exact:true}).click();await page.waitForFunction(()=>!dirty&&state.draft.pages[page].seo?.title);
 async function publish(){await page.locator('#publish').click();await page.locator('#confirmPublish').click();await page.waitForFunction(()=>!busy&&!document.querySelector('#publishDialog').open);}
 const publicURL='http://localhost:8123/cms/site.php?site='+site+'&page=index.html',sitemapURL='http://localhost:8123/cms/sitemap.php?site='+site;assert(!(await (await context.request.get(sitemapURL)).text()).includes('<loc>'));await publish();
 const response=await context.request.get(publicURL),html=await response.text();assert.equal(response.status(),200);assert(html.includes('<title>Поисковый заголовок &lt;script&gt;</title>'));assert(html.includes('content="Описание &amp; подробности"'));assert(html.includes('property="og:image" content="http://localhost:8123/cms/media/share.jpg"'));assert(html.includes('rel="canonical"'));assert(!html.includes('<script>'));
 let xml=await (await context.request.get(sitemapURL)).text();assert(xml.includes('site='+site+'&amp;page=index.html'));
 await page.locator('#seoButton').click();await page.getByLabel('Заголовок для поиска',{exact:true}).fill('Новый черновик');await page.getByLabel('Не индексировать страницу',{exact:true}).check();await page.getByRole('button',{name:'Сохранить SEO',exact:true}).click();await page.waitForFunction(()=>!dirty&&state.draft.pages[page].seo.noindex);assert((await (await context.request.get(publicURL)).text()).includes('Поисковый заголовок'));
 await publish();assert((await (await context.request.get(publicURL)).text()).includes('content="noindex, nofollow"'));assert(!(await (await context.request.get(sitemapURL)).text()).includes('<loc>'));
 const preview=await context.request.get(publicURL+'&cms-preview=1');assert.equal(preview.headers()['x-robots-tag'],'noindex, nofollow');assert(!(await preview.text()).includes('Новый черновик'));
 // Generated record metadata comes from the published record fields, without client execution.
 await page.evaluate(async()=>{state.draft.collections=[{id:'news',name:'Private',titleField:'title',fields:[{key:'title',label:'Title',type:'string',required:true},{key:'description',label:'Description',type:'text',required:false}],entries:[{id:'first',slug:'first',status:'published',values:{title:'Record title',description:'Record description'}}],template:[{block:{id:'text','type':'text',props:{}},bindings:{title:'title'}}],seo:{titleField:'title',descriptionField:'description',imageField:'',noindex:false}}];changed();await mutation('save');});await publish();
 const record=await (await context.request.get('http://localhost:8123/cms/site.php?site='+site+'&page=c-4-news-first.html')).text();assert(record.includes('<title>Record title</title>'));assert(record.includes('name="description" content="Record description"'));xml=await (await context.request.get(sitemapURL)).text();assert(xml.includes('c-4-news-first.html'));assert(!xml.includes('page=index.html'));
 await page.reload();await page.waitForFunction(()=>typeof canvasMain!=='undefined'&&canvasMain&&!building);assert.equal(await page.evaluate(()=>state.draft.pages[page].seo.noindex),true);assert.deepEqual(errors,[]);console.log('SEO browser/HTTP passed: editor settings, raw HTML metadata, publication isolation, noindex, preview privacy, sitemap and collection record metadata');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
