<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
start_secure_session();
$action=$_GET['action']??'health';
const OWNER='Иван Кириллов 414';
try{
 if($action==='health'){$count=(int)$pdo->query('SELECT COUNT(*) FROM products')->fetchColumn();json_response(['ok'=>true,'db'=>true,'products'=>$count,'php'=>PHP_VERSION]);}
 if($action==='setup_status'){$s=$pdo->prepare('SELECT id,username,password_hash,force_password_setup FROM admin_users WHERE username=? LIMIT 1');$s->execute([OWNER]);$u=$s->fetch();json_response(['ok'=>true,'setup_required'=>!$u||empty($u['password_hash'])||(int)$u['force_password_setup']===1]);}
 if($action==='login'&&$_SERVER['REQUEST_METHOD']==='POST'){$in=input_json();$username=trim((string)($in['username']??''));$password=(string)($in['password']??'');$s=$pdo->prepare('SELECT id,username,password_hash,role,is_active FROM admin_users WHERE username=? LIMIT 1');$s->execute([$username]);$u=$s->fetch();if(!$u||!(int)$u['is_active']||empty($u['password_hash'])||!password_verify($password,$u['password_hash']))json_response(['ok'=>false,'error'=>'invalid_credentials'],401);session_regenerate_id(true);$_SESSION['admin']=['id'=>(int)$u['id'],'username'=>$u['username'],'role'=>$u['role']];$_SESSION['csrf']=bin2hex(random_bytes(24));audit($pdo,'login','admin_user',(string)$u['id']);json_response(['ok'=>true,'admin'=>$_SESSION['admin'],'csrf'=>$_SESSION['csrf']]);}
 if($action==='password_change'&&$_SERVER['REQUEST_METHOD']==='POST'){$a=require_admin();csrf_check();$in=input_json();$p=(string)($in['new_password']??'');$p2=(string)($in['confirm_password']??'');if(strlen($p)<10)json_response(['ok'=>false,'error'=>'password_too_short'],422);if(!hash_equals($p,$p2))json_response(['ok'=>false,'error'=>'password_mismatch'],422);$s=$pdo->prepare('UPDATE admin_users SET password_hash=?,force_password_setup=0 WHERE id=? AND username=?');$s->execute([password_hash($p,PASSWORD_DEFAULT),(int)$a['id'],OWNER]);audit($pdo,'password_change','admin_user',(string)$a['id']);json_response(['ok'=>true]);}
 if($action==='logout'&&$_SERVER['REQUEST_METHOD']==='POST'){require_admin();csrf_check();audit($pdo,'logout');$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain']??'',(bool)$p['secure'],(bool)$p['httponly']);}session_destroy();json_response(['ok'=>true]);}
 if($action==='me'){$a=require_admin();json_response(['ok'=>true,'admin'=>$a,'csrf'=>$_SESSION['csrf']??'']);}
 if($action==='stats'){require_admin();$products=(int)$pdo->query('SELECT COUNT(*) FROM products WHERE is_active=1')->fetchColumn();$orders=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status='new'")->fetchColumn();json_response(['ok'=>true,'products'=>$products,'new_orders'=>$orders]);}
 if($action==='products'&&$_SERVER['REQUEST_METHOD']==='GET'){require_admin();$q=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['page']??1));$limit=40;$offset=($page-1)*$limit;if($q!==''){$s=$pdo->prepare('SELECT * FROM products WHERE title LIKE ? ORDER BY id DESC LIMIT '.$limit.' OFFSET '.$offset);$s->execute(['%'.$q.'%']);}else $s=$pdo->query('SELECT * FROM products ORDER BY id DESC LIMIT '.$limit.' OFFSET '.$offset);$rows=$s->fetchAll();foreach($rows as &$r){$r['images']=json_decode($r['images']?:'[]',true)?:[];$r['specs']=json_decode($r['specs']?:'{}',true)?:[];}json_response(['ok'=>true,'items'=>$rows,'page'=>$page]);}
 if($action==='settings'&&$_SERVER['REQUEST_METHOD']==='GET'){require_admin();$rows=$pdo->query('SELECT setting_key,setting_value FROM site_settings ORDER BY setting_key')->fetchAll();$out=[];foreach($rows as $r)$out[$r['setting_key']]=$r['setting_value'];json_response(['ok'=>true,'settings'=>$out]);}
 if($action==='settings_save'&&$_SERVER['REQUEST_METHOD']==='POST'){require_admin();csrf_check();$in=input_json();$s=$pdo->prepare('INSERT INTO site_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');foreach(($in['settings']??[]) as $k=>$v){if(preg_match('/^[a-z0-9_]{1,120}$/i',(string)$k))$s->execute([(string)$k,(string)$v]);}audit($pdo,'settings_save','settings');json_response(['ok'=>true]);}
 json_response(['ok'=>false,'error'=>'not_found'],404);
}catch(Throwable $e){error_log($e->__toString());if($pdo->inTransaction())$pdo->rollBack();json_response(['ok'=>false,'error'=>'server_error'],500);}
