<?php
declare(strict_types=1);
require_once __DIR__.'/order-schema.php';

$configFile = __DIR__ . '/config.php';
if (!is_file($configFile)) { http_response_code(500); exit('Server configuration is missing'); }
$config = require $configFile;
date_default_timezone_set($config['timezone']??'Asia/Yekaterinburg');

function db(): PDO { static $pdo=null; global $config; if($pdo instanceof PDO)return $pdo; $dsn=sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',$config['db_host'],(int)($config['db_port']??3306),$config['db_name']); $pdo=new PDO($dsn,$config['db_user'],$config['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]); $pdo->exec('SET time_zone = '.$pdo->quote($config['db_timezone']??'+05:00')); return $pdo; }
function table_columns(PDO $pdo,string $table): array { $out=[];foreach($pdo->query("SHOW COLUMNS FROM `$table`") as $r)$out[(string)$r['Field']]=true;return $out; }
function ensure_product_columns(PDO $pdo): void {
  $cols=table_columns($pdo,'products');
  $defs=[
    'name'=>"VARCHAR(500) NOT NULL DEFAULT ''",'source_id'=>'VARCHAR(255) NULL','slug'=>'VARCHAR(500) NULL','sku'=>'VARCHAR(255) NULL','brand'=>'VARCHAR(255) NULL','model'=>'VARCHAR(255) NULL','price'=>'DECIMAL(12,2) NOT NULL DEFAULT 0','old_price'=>'DECIMAL(12,2) NULL','short_description'=>'TEXT NULL','main_image'=>'TEXT NULL','sort_order'=>'INT NOT NULL DEFAULT 0','source_hash'=>'CHAR(64) NULL','catalog_snapshot'=>'CHAR(64) NULL','external_url'=>'VARCHAR(1000) NULL','price_rub'=>'INT NOT NULL DEFAULT 0','old_price_rub'=>'INT NULL','stock_qty'=>'INT NULL','stock_status'=>"VARCHAR(40) NOT NULL DEFAULT 'unknown'",'availability'=>"VARCHAR(40) NOT NULL DEFAULT 'unknown'",'category_path'=>'TEXT NULL','specs'=>'LONGTEXT NULL','description'=>'LONGTEXT NULL','images'=>'LONGTEXT NULL','is_active'=>'TINYINT(1) NOT NULL DEFAULT 1','created_at'=>'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP','updated_at'=>'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
  ];
  foreach($defs as $name=>$def){if(!isset($cols[$name])){$pdo->exec("ALTER TABLE products ADD COLUMN `$name` $def");$cols[$name]=true;}}
  try{$idx=[];foreach($pdo->query("SHOW INDEX FROM products") as $r)$idx[(string)$r['Key_name']]=true;if(!isset($idx['idx_source_hash']))$pdo->exec('CREATE INDEX idx_source_hash ON products(source_hash)');if(!isset($idx['idx_catalog_snapshot']))$pdo->exec('CREATE INDEX idx_catalog_snapshot ON products(catalog_snapshot)');if(!isset($idx['idx_active']))$pdo->exec('CREATE INDEX idx_active ON products(is_active)');if(!isset($idx['idx_stock_status']))$pdo->exec('CREATE INDEX idx_stock_status ON products(stock_status)');}catch(Throwable $e){error_log('index_migration_failed: '.$e->getMessage());}
}
function ensure_customer_columns(PDO $pdo): void {
  $cols=table_columns($pdo,'customers');
  $defs=[
    'last_name'=>'VARCHAR(120) NULL',
    'birth_date'=>'DATE NULL',
    'registration_source'=>"VARCHAR(40) NOT NULL DEFAULT 'website'",
    'consent_at'=>'DATETIME NULL',
    'qr_registered_at'=>'DATETIME NULL'
  ];
  foreach($defs as $name=>$def){if(!isset($cols[$name])){$pdo->exec("ALTER TABLE customers ADD COLUMN `$name` $def");$cols[$name]=true;}}
  $passwordColumn=null;foreach($pdo->query("SHOW COLUMNS FROM customers LIKE 'password_hash'") as $row){$passwordColumn=$row;break;}
  if($passwordColumn&&strtoupper((string)($passwordColumn['Null']??'NO'))!=='YES')$pdo->exec('ALTER TABLE customers MODIFY password_hash VARCHAR(255) NULL');
  try{$idx=[];foreach($pdo->query('SHOW INDEX FROM customers') as $r)$idx[(string)$r['Key_name']]=true;if(!isset($idx['idx_customer_phone']))$pdo->exec('CREATE INDEX idx_customer_phone ON customers(phone)');if(!isset($idx['idx_customer_source']))$pdo->exec('CREATE INDEX idx_customer_source ON customers(registration_source)');}catch(Throwable $e){error_log('customer_index_migration_failed: '.$e->getMessage());}
}
function ensure_schema(PDO $pdo): void {
$pdo->exec("CREATE TABLE IF NOT EXISTS admin_users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,username VARCHAR(120) NOT NULL UNIQUE,password_hash VARCHAR(255) NULL,role VARCHAR(30) NOT NULL DEFAULT 'owner',is_active TINYINT(1) NOT NULL DEFAULT 1,force_password_setup TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS site_settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(120) NOT NULL UNIQUE,setting_value LONGTEXT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS products (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,source_hash CHAR(64) NULL,catalog_snapshot CHAR(64) NULL,external_url VARCHAR(1000) NULL,title VARCHAR(500) NOT NULL DEFAULT '',price_rub INT NOT NULL DEFAULT 0,old_price_rub INT NULL,stock_qty INT NULL,stock_status VARCHAR(40) NOT NULL DEFAULT 'unknown',availability VARCHAR(40) NOT NULL DEFAULT 'unknown',category_path TEXT NULL,specs LONGTEXT NULL,description LONGTEXT NULL,images LONGTEXT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_source_hash (source_hash),INDEX idx_catalog_snapshot (catalog_snapshot),INDEX idx_title (title(191)),INDEX idx_price (price_rub),INDEX idx_active (is_active),INDEX idx_stock_status (stock_status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
ensure_product_columns($pdo);
$pdo->exec("CREATE TABLE IF NOT EXISTS customers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(200) NOT NULL,email VARCHAR(200) NOT NULL UNIQUE,phone VARCHAR(40) NULL,password_hash VARCHAR(255) NOT NULL,bonus_balance INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_customer_email(email)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
ensure_customer_columns($pdo);
$pdo->exec("CREATE TABLE IF NOT EXISTS customer_favorites (customer_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(customer_id,product_id),INDEX idx_fav_product(product_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS loyalty_transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,customer_id BIGINT UNSIGNED NOT NULL,amount INT NOT NULL,kind VARCHAR(40) NOT NULL,source_type VARCHAR(40) NULL,source_id VARCHAR(100) NULL,note VARCHAR(255) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_loyalty_customer(customer_id),INDEX idx_loyalty_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS product_reviews (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,customer_id BIGINT UNSIGNED NULL,product_id BIGINT UNSIGNED NOT NULL,rating TINYINT UNSIGNED NOT NULL,review_text TEXT NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending',bonus_awarded TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_review_product(product_id),INDEX idx_review_status(status),INDEX idx_review_customer(customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_number VARCHAR(40) NOT NULL UNIQUE,customer_name VARCHAR(200) NOT NULL,phone VARCHAR(40) NOT NULL,email VARCHAR(200) NULL,delivery_method VARCHAR(30) NOT NULL DEFAULT 'pickup',address TEXT NULL,comment TEXT NULL,status VARCHAR(30) NOT NULL DEFAULT 'new',total_rub INT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_status (status),INDEX idx_created (created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
try{$cols=table_columns($pdo,'orders');if(!isset($cols['customer_id']))$pdo->exec('ALTER TABLE orders ADD COLUMN customer_id BIGINT UNSIGNED NULL AFTER id');}catch(Throwable $e){error_log('orders_customer_migration_failed: '.$e->getMessage());}
$cols=table_columns($pdo,'orders');
if(!isset($cols['request_key']))$pdo->exec('ALTER TABLE orders ADD COLUMN request_key CHAR(64) NULL, ADD UNIQUE KEY idx_order_request(request_key)');
if(!isset($cols['request_hash']))$pdo->exec('ALTER TABLE orders ADD COLUMN request_hash CHAR(64) NULL');
$pdo->exec("CREATE TABLE IF NOT EXISTS order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NULL,title VARCHAR(500) NOT NULL,price_rub INT NOT NULL,quantity INT NOT NULL DEFAULT 1,line_total_rub INT NOT NULL,CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,INDEX idx_order (order_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS service_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,request_number VARCHAR(40) NOT NULL UNIQUE,name VARCHAR(200) NOT NULL,phone VARCHAR(40) NOT NULL,service_type VARCHAR(100) NOT NULL,bike VARCHAR(300) NOT NULL,problem TEXT NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'new',request_key CHAR(64) NOT NULL UNIQUE,request_hash CHAR(64) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_service_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS audit_log (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,admin_user_id INT UNSIGNED NULL,action VARCHAR(100) NOT NULL,entity_type VARCHAR(50) NULL,entity_id VARCHAR(100) NULL,payload LONGTEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_created (created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS auth_rate_limits (scope VARCHAR(40) NOT NULL,subject_hash CHAR(64) NOT NULL,attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,window_started_at DATETIME NOT NULL,blocked_until DATETIME NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(scope,subject_hash),INDEX idx_blocked_until(blocked_until)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
ensure_order_columns($pdo);
$stmt=$pdo->prepare("INSERT IGNORE INTO admin_users (username,password_hash,role,is_active,force_password_setup) VALUES (?,NULL,'owner',1,1)");$stmt->execute(['Иван Кириллов 414']);
}
function start_secure_session(): void { if(session_status()===PHP_SESSION_ACTIVE)return; ini_set('session.use_strict_mode','1'); ini_set('session.gc_maxlifetime',(string)(60*60*8)); session_name('PROFISPORT_ADMIN'); session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>true,'httponly'=>true,'samesite'=>'Strict']); session_start(); }
function json_response(array $data,int $status=200): never { http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit; }
function input_json(): array {$raw=file_get_contents('php://input',false,null,0,1048577)?:'';if(strlen($raw)>1048576)json_response(['ok'=>false,'error'=>'payload_too_large'],413);$data=json_decode($raw,true);return is_array($data)?$data:[];}
function require_admin(): array {start_secure_session();if(empty($_SESSION['admin']))json_response(['ok'=>false,'error'=>'unauthorized'],401);$s=db()->prepare('SELECT id,username,role FROM admin_users WHERE id=? AND is_active=1');$s->execute([(int)$_SESSION['admin']['id']]);$a=$s->fetch();if(!$a){$_SESSION=[];json_response(['ok'=>false,'error'=>'unauthorized'],401);}$_SESSION['admin']=$a;return $a;}
function csrf_check(): void {start_secure_session();$token=$_SERVER['HTTP_X_CSRF_TOKEN']??'';if(!$token||empty($_SESSION['csrf'])||!hash_equals($_SESSION['csrf'],$token))json_response(['ok'=>false,'error'=>'csrf'],403);}
function auth_rate_subject(string $identity=''): string { $ip=(string)($_SERVER['REMOTE_ADDR']??'unknown');return hash('sha256',$ip."\n".mb_strtolower(trim($identity),'UTF-8')); }
function auth_rate_check(PDO $pdo,string $scope,string $identity='',int $maxAttempts=5,int $windowSeconds=900): void {
  $key=auth_rate_subject($identity);$s=$pdo->prepare('SELECT attempts,UNIX_TIMESTAMP(window_started_at) AS started,UNIX_TIMESTAMP(blocked_until) AS blocked FROM auth_rate_limits WHERE scope=? AND subject_hash=? LIMIT 1');$s->execute([$scope,$key]);$row=$s->fetch();if(!$row)return;
  $now=time();if((int)($row['blocked']??0)>$now){header('Retry-After: '.max(1,(int)$row['blocked']-$now));json_response(['ok'=>false,'error'=>'rate_limited'],429);}
  if((int)$row['started']+$windowSeconds<=$now)return;
  if((int)$row['attempts']>=$maxAttempts)json_response(['ok'=>false,'error'=>'rate_limited'],429);
}
function auth_rate_failure(PDO $pdo,string $scope,string $identity='',int $maxAttempts=5,int $windowSeconds=900,int $blockSeconds=900): void {
  $key=auth_rate_subject($identity);$s=$pdo->prepare('SELECT attempts,UNIX_TIMESTAMP(window_started_at) AS started FROM auth_rate_limits WHERE scope=? AND subject_hash=? LIMIT 1');$s->execute([$scope,$key]);$row=$s->fetch();$now=time();
  if(!$row||(int)$row['started']+$windowSeconds<=$now){$q=$pdo->prepare('INSERT INTO auth_rate_limits(scope,subject_hash,attempts,window_started_at,blocked_until) VALUES(?,?,1,NOW(),NULL) ON DUPLICATE KEY UPDATE attempts=1,window_started_at=NOW(),blocked_until=NULL');$q->execute([$scope,$key]);return;}
  $attempts=(int)$row['attempts']+1;$blocked=$attempts>=$maxAttempts?(new DateTimeImmutable())->modify('+'.$blockSeconds.' seconds')->format('Y-m-d H:i:s'):null;$q=$pdo->prepare('UPDATE auth_rate_limits SET attempts=?,blocked_until=? WHERE scope=? AND subject_hash=?');$q->execute([$attempts,$blocked,$scope,$key]);
}
function auth_rate_clear(PDO $pdo,string $scope,string $identity=''): void { $s=$pdo->prepare('DELETE FROM auth_rate_limits WHERE scope=? AND subject_hash=?');$s->execute([$scope,auth_rate_subject($identity)]); }
function audit(PDO $pdo,string $action,?string $type=null,?string $id=null,array $payload=[]):void{try{$adminId=$_SESSION['admin']['id']??null;$s=$pdo->prepare('INSERT INTO audit_log (admin_user_id,action,entity_type,entity_id,payload) VALUES (?,?,?,?,?)');$s->execute([$adminId,$action,$type,$id,$payload?json_encode($payload,JSON_UNESCAPED_UNICODE):null]);}catch(Throwable $e){error_log('audit_failed: '.$e->getMessage());}}
$pdo=db();
if(!defined('PROFISPORT_SKIP_SCHEMA') || PROFISPORT_SKIP_SCHEMA!==true) ensure_schema($pdo);
