'use strict';
const $=s=>document.querySelector(s);
let state,csrf='',page='index.html',dirty=false,busy=false,previewWindow;
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function status(message,error=false){const el=state?$('#status'):$('#loginStatus');el.textContent=message;el.classList.toggle('error',error);}
async function api(action,body){const options={credentials:'same-origin',headers:{'X-CSRF-Token':csrf},signal:AbortSignal.timeout(15000)};if(body!==undefined){options.method='POST';if(body instanceof FormData)options.body=body;else {options.headers['Content-Type']='application/json';options.body=JSON.stringify(body);}}const r=await fetch('api.php?action='+action+(new URLSearchParams(location.search).has('site')?'&site='+encodeURIComponent(new URLSearchParams(location.search).get('site')):''),options);const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'Не удалось выполнить действие.'),{code:data.code});return data;}
const access=CMSAccess.mount({api,getState:()=>state,report:status});
function revision(){ $('#revision').textContent=`Черновик №${state.version} · Опубликовано: ${state.published_version||'ещё нет'}${dirty?' · Есть несохранённые изменения':''}`;}
function changed(){if(!access.permissions().edit)return;dirty=true;revision();recovery.capture();autosave.schedule();}
const autosave=CMSAutosave.create({
 snapshot(){return state&&dirty&&!busy&&access.permissions().edit?{draft:structuredClone(state.draft),version:state.version}:null;},
 save:sent=>api('save',sent),
 acknowledge(result,sent){state.version=result.version;state.published_version=result.published_version;dirty=JSON.stringify(state.draft)!==JSON.stringify(sent.draft);recovery.saved();revision();},
 notify(event,error){status(event==='saving'?'Сохраняю черновик…':event==='error'?'Автосохранение остановлено. '+error.message+' Правки остаются в редакторе. Откройте «Локальные копии» для сравнения версий или повторите сохранение после восстановления связи.':dirty?'Сохранено. Есть новые изменения.':'Черновик сохранён автоматически.',event==='error');}
});
const recovery=CMSRecovery.create({
 getState:()=>state,isDirty:()=>dirty,syncDraft:()=>{},
 settle:()=>autosave.settle(),resume:()=>{if(dirty)autosave.schedule();},loadRemote:()=>api('state'),report:status,
 async apply(remote,local){Object.assign(state,remote);access.apply();if(local&&!access.permissions().edit)throw Error('Нет права редактирования.');csrf=state.csrf;if(local)state.draft=structuredClone(local);dirty=!!local;autosave.reset();if(!state.manifest.pages[page])page=Object.keys(state.manifest.pages)[0];render(); if(dirty){recovery.capture();autosave.schedule();}revision();status(local?'Локальная копия восстановлена. Сохраняю черновик…':'Открыта серверная версия.');}
});
function render(){
 if(!Object.keys(state.manifest.pages).length){$('#pageTitle').textContent='Редактор полей';const link=element('a','Открыть визуальный редактор');link.href='index.html?site='+encodeURIComponent(state.site.key);$('#pages').replaceChildren(link);$('#blocks').hidden=true;$('#fields').replaceChildren(element('p','У этого сайта нет связанных текстовых полей. Страницы редактируются в визуальном редакторе.'));$('#preview').hidden=true;access.apply();revision();return;}
 $('#preview').hidden=false;
 $('#pageTitle').textContent=state.manifest.pages[page].title;$('#pages').replaceChildren();
 for(const [key,p] of Object.entries(state.manifest.pages)){const b=element('button',p.title,key===page?'active':'');b.onclick=()=>{page=key;render();};$('#pages').append(b);}
 const blocks=$('#blocks');blocks.replaceChildren();const bdata=state.draft.pages[page].blocks;blocks.hidden=!bdata.length||Array.isArray(state.draft.pages[page].layout);
 blocks.append(element('h2','Блоки страницы'));
 bdata.forEach((block,index)=>{const meta=state.manifest.pages[page].blocks.find(b=>b.id===block.id);const row=element('div',undefined,'block'),label=element('label'),check=element('input');check.type='checkbox';check.checked=block.visible;check.onchange=()=>{block.visible=check.checked;changed();};label.append(check,element('span',meta.label));row.append(label);for(const [text,delta] of [['↑',-1],['↓',1]]){const b=element('button',text,'secondary');b.setAttribute('aria-label',(delta<0?'Поднять: ':'Опустить: ')+meta.label);b.disabled=index+delta<0||index+delta>=bdata.length;b.onclick=()=>{[bdata[index],bdata[index+delta]]=[bdata[index+delta],bdata[index]];changed();render();};row.append(b);}blocks.append(row);});
 const fields=$('#fields');fields.replaceChildren();const groups=new Map();
 for(const f of state.manifest.pages[page].fields){let group=groups.get(f.group);if(!group){group=element('details');group.open=groups.size===0;group.append(element('summary',f.group));groups.set(f.group,group);fields.append(group);}const wrap=element('div',undefined,'field'),label=element('label',f.label),input=element(f.kind==='text'?'textarea':'input');input.value=state.draft.pages[page].fields[f.id];input.maxLength=12000;input.oninput=()=>{state.draft.pages[page].fields[f.id]=input.value;changed();};label.append(input);wrap.append(label);
  if(['image','background'].includes(f.kind)){const image=element('img');image.alt='Текущее изображение';image.hidden=!input.value;if(input.value)image.src=new URL(input.value,state.site_url).href;wrap.append(image);const upload=element('input');upload.type='file';upload.accept='image/jpeg,image/png,image/webp';upload.setAttribute('aria-label','Загрузить изображение');upload.onchange=async()=>{if(!upload.files[0])return;upload.disabled=true;try{const form=new FormData();form.append('file',upload.files[0]);const result=await api('upload',form);input.value=result.url;state.draft.pages[page].fields[f.id]=result.url;image.src=new URL(result.url,state.site_url).href;image.hidden=false;changed();status('Изображение загружено. Сохраните черновик.');}catch(e){status(e.message,true);}finally{upload.disabled=false;}};wrap.append(upload,element('small','JPG, PNG или WebP · до 5 МБ'));}
  group.append(wrap);
 }
 access.apply();revision();
}
async function load(){await autosave.settle();try{state=await api('state');}catch(error){if(error.code==='no_sites'){access.noSites();return;}if(error.code==='forbidden'){await access.unavailable();return;}throw error;}access.apply();autosave.reset();csrf=state.csrf;dirty=false;$('#login').hidden=true;$('#app').hidden=false;$('#siteLink').href=state.site_url;render();access.apply();if(access.permissions().edit)await recovery.offer();}
async function mutation(action,extra={}){if(!access.permissions()[action==='publish'?'publish':'edit']){status('Недостаточно прав для этого действия.',true);return false;}await autosave.settle();if(busy)return false;if(action==='save')extra={...extra,draft:structuredClone(state.draft)};busy=true;document.querySelectorAll('#app button, #app input, #app textarea').forEach(b=>b.disabled=true);try{const result=await api(action,{version:state.version,...extra});Object.assign(state,result);dirty=false;autosave.reset();recovery.saved();render();status(action==='publish'?'Изменения опубликованы.':action==='restore'?'Версия восстановлена в черновик.':'Черновик сохранён.');return true;}catch(e){status(e.message,true);return false;}finally{busy=false;document.querySelectorAll('#app button, #app input, #app textarea').forEach(b=>b.disabled=false);render();}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));const result=await api('login',data);csrf=result.csrf;e.target.reset();await load();}catch(e){status(e.message,true);}finally{b.disabled=false;}};
$('#save').onclick=()=>mutation('save',{draft:state.draft});
$('#publish').onclick=async()=>{if(dirty&&!(await mutation('save',{draft:state.draft})))return;if(confirm('Опубликовать сохранённые изменения на сайте?'))await mutation('publish');};
$('#logout').onclick=async()=>{await autosave.settle();if(dirty&&!confirm('Выйти без сохранения изменений?')){autosave.schedule();return;}try{await api('logout',{});location.reload();}catch(e){status(e.message,true);}};
$('#historyBtn').onclick=async()=>{try{const data=await api('history');$('#historyList').replaceChildren();for(const item of data.items){const row=element('div',undefined,'historyRow');row.append(element('span',`№${item.id} · ${item.created_at} · ${item.actor} · ${{install:'Исходная версия',save:'Черновик',publish:'Публикация',restore:'Восстановление'}[item.action]||item.action}`));const b=element('button','Восстановить','secondary');b.onclick=async()=>{if(confirm('Заменить текущий черновик этой версией?')){if(await mutation('restore',{id:item.id}))$('#history').close();}};row.append(b);$('#historyList').append(row);}if(!data.items.length)$('#historyList').append(element('p','Сохранённых изменений пока нет.'));$('#history').showModal();}catch(e){status(e.message,true);}};
$('#closeHistory').onclick=()=>$('#history').close();
function previewPayload(){const p=state.manifest.pages[page],draft=state.draft.pages[page];return {layout:draft.layout?.map(r=>CMSComponents.render(r,state.draft.components,state.draft.collections)),sections:(state.templates?.[page]?.sections||[]).map(s=>({id:s.id,selector:s.selector})),fields:p.fields.filter(f=>draft.fields[f.id]!==f.value).map(f=>({selector:f.selector,kind:f.kind,value:draft.fields[f.id]})),blocks:draft.blocks.map(b=>{const m=p.blocks.find(m=>m.id===b.id);return{selector:m.selector,visible:b.visible,changed:b.visible!==m.visible};})};}
$('#preview').onclick=()=>{const url=new URL(page,state.site_url);url.searchParams.set('cms-preview','1');previewWindow=window.open(url.href,'cms-preview');if(!previewWindow)status('Разрешите открытие окна предпросмотра.',true);};
window.addEventListener('message',event=>{if(!state||event.source!==previewWindow||event.origin!==new URL(state.site_url).origin||event.data?.type!=='cms-ready')return;previewWindow.postMessage({type:'cms-preview',payload:previewPayload()},event.origin);});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{const s=await api('session');csrf=s.csrf;$('#loginForm button').disabled=false;if(s.authenticated)await load();}catch(e){status(e.message,true);}})();
