'use strict';
const liveBasePrepare=prepareHTML,liveBaseProperties=properties,liveBaseBind=bindCanvasWorkspace;
const liveFonts={Arial:'Arial, sans-serif',Verdana:'Verdana, sans-serif',Georgia:'Georgia, serif',Trebuchet:'Trebuchet MS, sans-serif',Times:'Times New Roman, serif'};
const liveCss={color:'color',backgroundColor:'background-color',fontFamily:'font-family',fontSize:'font-size',fontWeight:'font-weight',textAlign:'text-align',borderRadius:'border-radius'};
function liveDraft(){return state.draft.pages[page];}
function liveEntry(selector,create=false){const all=liveDraft().elements||(liveDraft().elements=[]);let item=all.find(x=>x.selector===selector);if(!item&&create){item={selector,hidden:false};all.push(item);}return item;}
function liveFields(model){const ids=(model?.getAttributes?.()['data-cms-fields']||'').split(',');return pageMeta().fields.filter(f=>ids.includes(f.id));}
function liveAncestor(model,test){let n=model;while(n){if(test(n))return n;n=n.parent?.();}return null;}
function liveAction(model){const tile=liveAncestor(model,n=>(n.getClasses?.()||[]).includes('categoryTile')),target=tile||model,field=liveFields(target)[0]||liveFields(model)[0];return{model:target,selector:field?.selector||null,root:rootSection(model)};}
function liveStyle(model){const field=liveFields(model)[0],root=rootSection(model),section=state.templates?.[page]?.sections?.find(s=>s.id===root?.get('recipe')?.id);return{model,root,selector:field?.selector||section?.selector||null};}
function liveApply(doc,draft){const get=s=>{try{return doc.querySelector(s);}catch{return null;}};for(const item of draft.elements||[]){const n=get(item.selector);if(!n)continue;if(item.hidden)n.style.setProperty('display','none','important');for(const [k,v]of Object.entries(item.style||{})){if(liveCss[k])n.style.setProperty(liveCss[k],k==='fontFamily'?liveFonts[v]:v);}}for(const order of draft.orders||[]){const parent=get(order.parent),nodes=(order.selectors||[]).map(get);if(parent&&nodes.every(n=>n?.parentElement===parent))nodes.forEach(n=>parent.append(n));}}
prepareHTML=function(html){const out=liveBasePrepare(html),doc=new DOMParser().parseFromString(out,'text/html');liveApply(doc,liveDraft());return doc.body.innerHTML;};
function liveSetStyle(target,key,value){if(!target.selector)return;const entry=liveEntry(target.selector,true);entry.style??={};entry.style[key]=value;target.model.addStyle({[liveCss[key]]:key==='fontFamily'?liveFonts[value]:value});changed();}
function liveStylePanel(model){const target=liveStyle(model),panel=$('#properties');panel.replaceChildren(el('h3','Стиль элемента'),el('p','Изменения сохраняются вместе с черновиком.','hint'));if(!target.selector){panel.append(el('p','Выберите текст, изображение или секцию.','hint'));showProperties('Оформление');return;}const current=liveEntry(target.selector)?.style||{};for(const [label,key,fallback]of [['Цвет текста','color','#172033'],['Фон','backgroundColor','#ffffff']])panel.append(inputField(label,current[key]||fallback,v=>liveSetStyle(target,key,v),'color'));for(const [key,label,options]of [['fontFamily','Шрифт',{Arial:'Arial',Verdana:'Verdana',Georgia:'Georgia',Trebuchet:'Trebuchet MS',Times:'Times New Roman'}],['fontSize','Размер',{'14px':'14 px','16px':'16 px','18px':'18 px','24px':'24 px','32px':'32 px','48px':'48 px'}],['fontWeight','Насыщенность',{'400':'Обычный','500':'Средний','600':'Полужирный','700':'Жирный','800':'Очень жирный'}],['textAlign','Выравнивание',{left:'Слева',center:'По центру',right:'Справа'}]]){const wrap=el('label',label),select=el('select');for(const [v,t]of Object.entries(options)){const o=el('option',t);o.value=v;select.append(o);}select.value=current[key]||Object.keys(options)[0];select.onchange=()=>liveSetStyle(target,key,select.value);wrap.append(select);panel.append(wrap);}showProperties('Оформление');}
function liveCategorySelectors(){return [...new Set(pageMeta().fields.map(f=>f.selector).filter(s=>/^#categoryTiles > a:nth-child\([0-9]+\)$/.test(s)))];}
function liveMoveCard(target,delta){const defaults=liveCategorySelectors(),order=(liveDraft().orders||[]).find(x=>x.parent==='#categoryTiles')?.selectors?.slice()||defaults.slice(),at=order.indexOf(target.selector);if(at<0||!order[at+delta])return;[order[at],order[at+delta]]=[order[at+delta],order[at]];liveDraft().orders??=[];const saved=liveDraft().orders.find(x=>x.parent==='#categoryTiles');if(saved)saved.selectors=order;else liveDraft().orders.push({parent:'#categoryTiles',selectors:order});changed();renderPage();}
function liveHide(model){const target=liveAction(model),recipe=target.root?.get('recipe');if(target.selector){const item=liveEntry(target.selector,true);item.hidden=true;target.model.addStyle({display:'none'});changed();status('Элемент скрыт. Его можно вернуть через «Настройки».');return;}if(recipe?.type==='existing'){recipe.visible=false;target.root.set('recipe',{...recipe});target.root.addStyle({display:'none'});sync();changed();}else if(recipe){target.root.remove();sync();changed();}}
function liveHiddenPanel(){const panel=$('#properties');panel.replaceChildren(el('h3','Скрытые элементы'));const rows=(liveDraft().elements||[]).filter(x=>x.hidden);if(!rows.length)panel.append(el('p','На странице нет скрытых элементов.','hint'));for(const item of rows){const field=pageMeta().fields.find(f=>f.selector===item.selector),row=el('div',undefined,'live-restore');row.append(el('span',field?.label||'Элемент страницы'),actionButton('Показать',()=>{item.hidden=false;if(!item.style)liveDraft().elements=liveDraft().elements.filter(x=>x!==item);changed();renderPage();}));panel.append(row);}showProperties('Настройки');}
properties=function(model){if(!model||building)return;contextModel=model;const root=rootSection(model);if(root){currentSectionId=root.get('recipe').id;renderSectionJump();}const bar=$('#contextTools');bar.replaceChildren();if(!root){bar.hidden=true;return;}const fields=liveFields(model),action=liveAction(model),recipe=root.get('recipe'),edit=model.get('idEdit');if(fields.some(f=>['text','link'].includes(f.kind))||(recipe.type!=='existing'&&edit?.key!=='image'))bar.append(actionButton('✎ Текст',()=>contextualEditor(model,'text')));if(fields.some(f=>['image','background'].includes(f.kind))||(recipe.type!=='existing'&&(edit?.key==='image'||!recipe.props.items)))bar.append(actionButton('▧ Фото',()=>contextualEditor(model,'photo')));bar.append(actionButton('A Стиль',()=>liveStylePanel(model)));if(action.selector&&liveCategorySelectors().includes(action.selector))bar.append(actionButton('↑ Выше',()=>liveMoveCard(action,-1)),actionButton('↓ Ниже',()=>liveMoveCard(action,1)));bar.append(actionButton('⊘ Скрыть',()=>liveHide(model)),actionButton('Настройки',liveHiddenPanel));bar.hidden=!$('#editDialog').open;positionTools();};
function liveConfigure(){canvasMain?.components().forEach(root=>{root.set({draggable:'.cms-canvas-main',selectable:true,hoverable:true});root.find?.('#categoryTiles').forEach(box=>{box.set({droppable:'.categoryTile'});box.find('.categoryTile').forEach(tile=>tile.set({draggable:'#categoryTiles',droppable:false,selectable:true,hoverable:true}));});});}
bindCanvasWorkspace=function(){liveBaseBind();liveConfigure();const doc=editor?.Canvas.getDocument();if(doc&&!doc.documentElement.dataset.liveEdit){doc.documentElement.dataset.liveEdit='1';const style=doc.createElement('style');style.textContent='[data-cms-fields],.categoryTile,.cms-block{cursor:pointer!important}.categoryTile:hover,.cms-block:hover{outline:2px solid #19a987!important;outline-offset:2px}';doc.head.append(style);}};
const liveRender=renderPage;renderPage=async function(){await liveRender();liveConfigure();};
