/* ID Studio: section cards, contextual editing and a visual insertion library.
   The existing safe draft/API contract remains the source of truth. */
'use strict';
let currentSectionId=null,contextModel=null,boardTimer=null,sectionPropertiesModel=null;
const baseRenderPage=renderPage,baseRenderLayers=renderLayers,baseProperties=properties,baseChanged=changed,baseMutation=mutation,baseStatus=status;
function sectionModels(){return canvasMain?.components().models.filter(m=>m.get('recipe'))||[];}
function rootSection(model){let m=model;while(m&&!m.get('recipe'))m=m.parent();return m?.get('recipe')?m:null;}
function sectionName(recipe){if(recipe.type!=='existing')return recipe.props.title||labels[recipe.type]||'Секция';const section=state.templates[page]?.sections.find(s=>s.id===recipe.id);if(section?.selector==='#mobileSearch')return 'Поиск на телефоне';if(section){const doc=new DOMParser().parseFromString(sectionHTML(recipe),'text/html');doc.querySelectorAll('br').forEach(n=>n.replaceWith(doc.createTextNode(' ')));const heading=doc.querySelector('h1,h2,h3')?.textContent.trim().replace(/\s+/g,' ');if(heading)return heading;}return section?.label||'Элемент сайта';}
function sectionHTML(recipe){if(recipe.type==='existing'){const t=state.templates[page]?.sections.find(s=>s.id===recipe.id);return t?prepareHTML(t.html):'';}return CMBlocks.html(recipe,state.site_url);}
function previewDocument(recipes,library=false){const t=library?null:state.templates[page];const html=recipes.filter(r=>r.visible!==false).map(sectionHTML).join('');return '<!doctype html><html><head><meta charset="utf-8">'+(t?.styles||[]).map(h=>'<link rel="stylesheet" href="'+CMBlocks.esc(abs(h))+'">').join('')+'<style>'+CMBlocks.css+'\n'+(t?.css||'')+'\nhtml,body{margin:0!important;overflow:hidden!important;min-height:0!important}body{pointer-events:none}main{margin-top:0!important}*{animation:none!important;transition:none!important}'+ '</style></head><body class="'+CMBlocks.esc(t?.bodyClass||'')+'"><main class="'+CMBlocks.esc(t?.mainClass||'')+'">'+html+'</main></body></html>';}
const thumbObserver=new ResizeObserver(entries=>{for(const entry of entries){const frame=entry.target.querySelector('iframe');if(frame)frame.style.transform=`scale(${entry.contentRect.width/1120})`;}});
function thumbnail(recipes,library=false,overview=false){const box=el('div',undefined,'visual-thumb'+(overview?' overview-thumb':'')),frame=el('iframe');frame.setAttribute('sandbox','');frame.setAttribute('tabindex','-1');frame.setAttribute('aria-hidden','true');frame.title='Миниатюра секции';frame.loading='lazy';frame.srcdoc=previewDocument(recipes,library);box.append(frame);thumbObserver.observe(box);return box;}
function clearThumbnails(container){container.querySelectorAll('.visual-thumb').forEach(n=>thumbObserver.unobserve(n));container.replaceChildren();}
function boardRefreshSoon(){clearTimeout(boardTimer);boardTimer=setTimeout(()=>{if(!$('#editDialog').open&&!$('#libraryDialog').open)buildBoard();},200);}
function actionButton(text,fn,cls){const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;}
function buildBoard(){if(!state||!canvasMain)return;const grid=$('#sectionCards');clearThumbnails(grid);const models=sectionModels();$('#sectionCount').textContent=models.length+' секций';models.forEach((m,i)=>{const r=m.get('recipe'),card=el('article',undefined,'section-card'+(r.visible===false?' section-hidden':''));card.dataset.sectionId=r.id;const heading=el('header'),number=el('span',String(i+1),'section-number'),label=el('div');label.append(el('h2',sectionName(r)),el('p',r.visible===false?'Скрыта на сайте':r.type==='existing'?'Секция подключённого сайта':labels[r.type],'hint'));heading.append(number,label);card.append(heading);const body=el('div',undefined,'section-card-body'),preview=thumbnail([r.visible===false?{...r,visible:true}:r]);const overlay=actionButton('Открыть секцию «'+sectionName(r)+'»',()=>openSection(r.id),'thumb-open');preview.append(overlay);const actions=el('div',undefined,'section-actions');actions.append(actionButton('✎ Изменить',()=>openSection(r.id),'edit-card-button'));for(const [title,delta] of [['↑ Выше',-1],['↓ Ниже',1]]){const b=actionButton(title,()=>moveSection(r.id,delta));b.disabled=i+delta<0||i+delta>=models.length;actions.append(b);}actions.append(actionButton('＋ После',()=>openLibrary(i+1),'insert-after-card'));body.append(preview,actions);card.append(body);grid.append(card);});if(!models.length){const empty=el('div',undefined,'empty-board');empty.append(el('h2','Начнём с первой секции'),el('p','Откройте библиотеку и выберите подходящий внешний вид.'),actionButton('＋ Открыть библиотеку',()=>openLibrary(0),'primary'));grid.append(empty);}const overview=$('#pageOverview');clearThumbnails(overview);if(models.length)overview.append(thumbnail(models.map(m=>m.get('recipe')),false,true));renderSectionJump();}
function moveSection(id,delta){if(busy)return;const models=sectionModels(),index=models.findIndex(m=>m.get('recipe').id===id);if(index<0||index+delta<0||index+delta>=models.length)return;models[index].move(canvasMain,{at:index+delta});sync();changed();buildBoard();status('Порядок секций изменён. Сохраните черновик.');requestAnimationFrame(()=>$('#sectionCards').querySelector(`[data-section-id="${id}"] .edit-card-button`)?.focus({preventScroll:true}));}
function renderSectionJump(){const select=$('#sectionJump');select.replaceChildren();sectionModels().forEach((m,i)=>{const r=m.get('recipe'),o=el('option',`${i+1}. ${sectionName(r)}`);o.value=r.id;select.append(o);});if(currentSectionId)select.value=currentSectionId;const index=sectionModels().findIndex(m=>m.get('recipe').id===currentSectionId);$('#previousSection').disabled=index<=0;$('#nextSection').disabled=index<0||index>=sectionModels().length-1;}
function closeProperties(){$('#floatingProperties').hidden=true;sectionPropertiesModel=null;}
function showSectionProperties(model){contextModel=model;sectionPropertiesModel=model;baseProperties(model);showProperties('Настройки секции');}
function showProperties(title){$('#propertyTitle').textContent=title||'Редактирование';$('#floatingProperties').hidden=false;positionTools();}
function selectSection(id){const m=sectionModels().find(m=>m.get('recipe').id===id);if(!m)return;currentSectionId=id;$('#editingTitle').textContent=sectionName(m.get('recipe'));renderSectionJump();editor.select(m);properties(m);requestAnimationFrame(()=>{m.getEl()?.scrollIntoView({block:'start',behavior:'instant'});positionTools();});}
function openSection(id){if(busy)return;const dialog=$('#editDialog');if(!dialog.open)dialog.showModal();editor.refresh();currentSectionId=id||sectionModels()[0]?.get('recipe').id;selectSection(currentSectionId);setTimeout(()=>{editor.refresh();selectSection(currentSectionId);},80);}
function finishEditing(){sync();$('#editDialog').close();currentSectionId=null;contextModel=null;closeProperties();$('#contextTools').hidden=true;buildBoard();}
function canvasScroll(delta){const doc=editor?.Canvas.getDocument();doc?.defaultView?.scrollBy({top:delta*doc.documentElement.clientHeight*.7,behavior:'smooth'});}
function navigateSection(delta){const models=sectionModels(),i=models.findIndex(m=>m.get('recipe').id===currentSectionId);if(models[i+delta])selectSection(models[i+delta].get('recipe').id);}
function positionTools(){if(!$('#editDialog').open||!contextModel)return;const node=contextModel.getEl(),frame=editor.Canvas.getFrameEl();if(!node||!frame)return;const rect=node.getBoundingClientRect(),fr=frame.getBoundingClientRect(),stage=$('.edit-stage').getBoundingClientRect(),toolbar=$('#contextTools'),panel=$('#floatingProperties');const x=Math.max(12,Math.min(fr.left+rect.left-stage.left,stage.width-360)),y=Math.max(12,Math.min(fr.top+rect.top-stage.top-48,stage.height-70));toolbar.style.left=x+'px';toolbar.style.top=y+'px';panel.style.left=Math.max(12,Math.min(x,stage.width-380))+'px';panel.style.top=Math.min(y+48,Math.max(12,stage.height-420))+'px';panel.style.maxHeight=Math.max(160,stage.height-parseFloat(panel.style.top)-12)+'px';}
function mappedFields(model){const ids=(model?.getAttributes()['data-cms-fields']||'').split(',');return pageMeta().fields.filter(f=>ids.includes(f.id));}
function configureNewModels(root){const r=root.get('recipe');if(!r||r.type==='existing')return;const mark=(m,key,index=null)=>{if(!m)return;m.set({selectable:true,hoverable:true,idEdit:{key,index},editable:false});};mark(root.find('h2')[0],'title');const paragraphs=root.find('.cms-inner > p');mark(paragraphs[0],'text');if(r.type==='split'){mark(root.find('.cms-split p')[0],'text');mark(root.find('.cms-split img')[0],'image');}else if(r.type==='columns'){root.find('.cms-columns p').forEach((m,i)=>mark(m,i?'text2':'text'));}else if(!r.props.items)mark(root.find('img')[0],'image');if(r.props.items){const containers=['faq'].includes(r.type)?root.find('details'):root.find('.cms-grid')[0]?.components().models||[];containers.forEach((item,i)=>{mark(item.find('h3')[0]||item.find('figcaption')[0]||item.find('summary')[0]||item.find('cite')[0],'title',i);mark(item.find('p')[0],'text',i);mark(item.find('img')[0],'image',i);});}mark(root.find('.cms-inner > .cms-button')[0],'label');}
function updateRecipe(root,key,value,index=null){const r=structuredClone(root.get('recipe'));if(index===null)r.props[key]=value;else if(r.props.items?.[index])r.props.items[index][key]=value;root.set('recipe',r);root.components(CMBlocks.html(r,state.site_url));root.components().forEach(lock);configureNewModels(root);sync();changed();contextModel=root;positionTools();}
function contextualEditor(model,kind){const root=rootSection(model);if(!root)return;const recipe=root.get('recipe'),panel=$('#properties');panel.replaceChildren();const fields=mappedFields(model).filter(f=>kind==='photo'?['image','background','alt'].includes(f.kind):['text','link'].includes(f.kind));if(recipe.type==='existing'&&fields.length){for(const field of fields){panel.append(inputField(field.label,fieldValue(field.id),v=>updateMapped(field.id,v),field.kind==='text'?'textarea':'text'));if(['image','background'].includes(field.kind))panel.append(imageUpload(v=>{updateMapped(field.id,v);contextualEditor(model,kind);}));}showProperties(kind==='photo'?'Заменить изображение':'Изменить текст');return;}
if(recipe.type!=='existing'){const target=model.get('idEdit')||{},index=target.index??null,p=index===null?recipe.props:recipe.props.items?.[index]||recipe.props;if(kind==='photo'){panel.append(inputField('Адрес изображения',p.image,v=>updateRecipe(root,'image',v,index)),imageUpload(v=>{updateRecipe(root,'image',v,index);contextModel=root;closeProperties();status('Изображение заменено.');}),inputField('Описание изображения',p.alt,v=>updateRecipe(root,'alt',v,index)));}else if(kind==='text'){const keys=target.key&&target.key!=='image'?[target.key]:['title','text'];for(const key of keys)panel.append(inputField(({title:'Заголовок',text:'Текст',text2:'Вторая колонка',label:'Текст кнопки'})[key]||key,p[key],v=>updateRecipe(root,key,v,index),key==='text'||key==='text2'?'textarea':'text'));}else{for(const [key,label,fallback] of [['background','Фон','#ffffff'],['color','Цвет текста','#172033'],['accent','Цвет кнопки','#2463eb']])panel.append(inputField(label,p[key]||fallback,v=>updateRecipe(root,key,v),'color'));}showProperties(kind==='photo'?'Изображение':kind==='text'?'Текст':'Оформление');return;}
baseProperties(model);showProperties('Настройки секции');}
properties=function(model){if(!model||building)return;if(sectionPropertiesModel===model&&!$('#floatingProperties').hidden){showSectionProperties(model);return;}contextModel=model;const root=rootSection(model);if(root){currentSectionId=root.get('recipe').id;$('#editingTitle').textContent=sectionName(root.get('recipe'));renderSectionJump();}closeProperties();const toolbar=$('#contextTools');toolbar.replaceChildren();if(!root){toolbar.hidden=true;return;}const r=root.get('recipe'),fields=mappedFields(model),target=model.get('idEdit');if(fields.some(f=>['text','link'].includes(f.kind))||(r.type!=='existing'&&target?.key!=='image'))toolbar.append(actionButton('✎ Изменить текст',()=>contextualEditor(model,'text')));if(fields.some(f=>['image','background'].includes(f.kind))||(r.type!=='existing'&&(target?.key==='image'||!r.props.items)))toolbar.append(actionButton('▧ Заменить фото',()=>contextualEditor(model,'photo')));if(r.type!=='existing')toolbar.append(actionButton('◐ Оформление',()=>contextualEditor(root,'style')));toolbar.append(actionButton('Настройки секции',()=>showSectionProperties(root)));toolbar.hidden=!$('#editDialog').open;positionTools();};
function bindCanvasWorkspace(){if(!editor)return;sectionModels().forEach(configureNewModels);const doc=editor.Canvas.getDocument();if(doc&&!doc.documentElement.dataset.idWorkspace){doc.documentElement.dataset.idWorkspace='1';const style=doc.createElement('style');style.textContent='html,body{overflow-y:auto!important;scrollbar-gutter:stable}::-webkit-scrollbar{width:16px}::-webkit-scrollbar-track{background:#e6eaf0}::-webkit-scrollbar-thumb{background:#8895a5;border:3px solid #e6eaf0;border-radius:10px}[data-cms-fields]{cursor:pointer!important}';doc.head.append(style);doc.defaultView.addEventListener('scroll',positionTools,{passive:true});doc.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='PageDown'||e.key==='PageUp'){e.preventDefault();canvasScroll(e.key==='PageDown'?1:-1);}if(e.key==='Escape'){e.preventDefault();finishEditing();}});}if($('#editDialog').open){const models=sectionModels();if(!models.some(m=>m.get('recipe').id===currentSectionId))currentSectionId=models[0]?.get('recipe').id||null;if(currentSectionId)selectSection(currentSectionId);else finishEditing();}}
renderPage=async function(){await baseRenderPage();buildBoard();bindCanvasWorkspace();editor.on('load',bindCanvasWorkspace);editor.on('component:add component:remove',m=>{clearTimeout(editor.idAnnotateTimer);editor.idAnnotateTimer=setTimeout(()=>{sectionModels().forEach(configureNewModels);if(m.get('recipe')&&$('#editDialog').open&&!sectionModels().some(s=>s.get('recipe').id===currentSectionId))bindCanvasWorkspace();},50);});};
renderLayers=function(){baseRenderLayers();boardRefreshSoon();};
changed=function(){baseChanged();$('#editState').textContent=dirty?'Есть несохранённые изменения':'Сохранено';boardRefreshSoon();};
status=function(message,error=false){baseStatus(message,error);if($('#editDialog').open){$('#editState').textContent=message;$('#editState').classList.toggle('error',error);}};
mutation=async function(action,extra={}){const edit=$('#editDialog');edit.inert=true;try{return await baseMutation(action,extra);}finally{edit.inert=false;}};
const libraryDescriptions={hero:'Крупный заголовок, фотография и кнопка',text:'Заголовок и свободный текст',image:'Большая фотография с описанием',columns:'Два текстовых столбца',cta:'Предложение и кнопка действия',contacts:'Адрес, часы работы и контакты',spacer:'Свободное пространство между секциями',gallery:'Сетка фотографий с подписями',cards:'Карточки услуг или преимуществ',faq:'Раскрывающиеся вопросы и ответы',pricing:'Карточки тарифов и условий',testimonials:'Отзывы с именами авторов',metrics:'Важные цифры и показатели',split:'Изображение рядом с текстом'};
function libraryRecipe(type){const props=CMBlocks.defaults(type),media=knownMedia().filter(m=>m.url),photo=media[0]?.url||'';props.title=({hero:'Ваша история начинается здесь',gallery:'Галерея',cards:'Почему выбирают нас',split:'Расскажите о главном',cta:'Сделаем следующий шаг',contacts:'Будем рады видеть вас'})[type]||labels[type];props.text=type==='spacer'?'':'Пример содержимого. Замените его своим текстом.';if(['hero','image','split'].includes(type))props.image=photo;if(props.items)props.items=props.items.map((item,i)=>({...item,title:type==='metrics'?['10+','24/7','100%'][i]:type==='faq'?'Частый вопрос '+(i+1):'Заголовок '+(i+1),image:['gallery','cards'].includes(type)?media[i%Math.max(media.length,1)]?.url||'':'',text:'Короткое описание'}));return{id:'library-preview',type,props};}
function renderLibrary(){const grid=$('#libraryCards');clearThumbnails(grid);const query=$('#blockSearch').value.trim().toLowerCase(),category=$('#blockCategory').value;for(const [type,meta] of Object.entries(CMBlocks.catalog)){if(query&&!`${meta[0]} ${libraryDescriptions[type]}`.toLowerCase().includes(query)||category&&meta[1]!==category)continue;const card=el('article',undefined,'library-card');card.append(thumbnail([libraryRecipe(type)],true),el('h3',meta[0]),el('p',libraryDescriptions[type],'hint'),actionButton('Добавить · '+meta[0],()=>insertFromLibrary(type),'primary'));grid.append(card);}if(!grid.children.length)grid.append(el('p','Ничего не найдено. Попробуйте другую категорию.','hint'));document.querySelectorAll('#categoryChips button').forEach(b=>b.classList.toggle('active',b.dataset.category===category));}
function insertionPreview(){const container=$('#insertContext');clearThumbnails(container);const index=Number($('#insertPosition').value),models=sectionModels();if(index>0&&models[index-1]){container.append(el('p','После: '+sectionName(models[index-1].get('recipe')),'hint'),thumbnail([models[index-1].get('recipe')]));}else container.append(el('p','В начале страницы','hint'));}
function openLibrary(index=sectionModels().length){if(busy)return;sync();const select=$('#insertPosition');select.replaceChildren();const first=el('option','В начало страницы');first.value='0';select.append(first);sectionModels().forEach((m,i)=>{const o=el('option',`После ${i+1}. ${sectionName(m.get('recipe'))}`);o.value=String(i+1);select.append(o);});select.value=String(Math.max(0,Math.min(index,sectionModels().length)));$('#libraryDialog').showModal();renderLibrary();insertionPreview();}
function insertFromLibrary(type){if(busy)return;if(sectionModels().length>=100){status('На странице допускается до 100 секций.',true);return;}const r={id:'new-'+crypto.randomUUID(),type,props:CMBlocks.defaults(type)},m=modelFor(r),index=Number($('#insertPosition').value);building=true;canvasMain.append(m,{at:index});building=false;configureNewModels(m);sync();changed();$('#libraryDialog').close();buildBoard();openSection(r.id);status('Секция добавлена в выбранное место. Нажмите на текст или откройте настройки.');}
filterBlocks=function(){if($('#libraryDialog').open)renderLibrary();};
$('#blockSearch').oninput=renderLibrary;$('#blockCategory').onchange=renderLibrary;$('#insertPosition').onchange=insertionPreview;
for(const [value,label] of [['','Все'],['Основное','Основное'],['Медиа','Фото и галереи'],['Композиции','Карточки и списки']]){const button=actionButton(label,()=>{$('#blockCategory').value=value;renderLibrary();});button.dataset.category=value;$('#categoryChips').append(button);}
$('#openLibrary').onclick=()=>openLibrary();$('#addSectionTop').onclick=()=>openLibrary();$('#addSectionBottom').onclick=()=>openLibrary();$('#insertAfter').onclick=()=>openLibrary(Math.max(0,sectionModels().findIndex(m=>m.get('recipe').id===currentSectionId)+1));
$('#closeEditor').onclick=finishEditing;$('#editDialog').addEventListener('cancel',e=>{e.preventDefault();finishEditing();});$('#closeProperties').onclick=closeProperties;
$('#sectionSettings').onclick=()=>{const m=sectionModels().find(m=>m.get('recipe').id===currentSectionId);if(m)showSectionProperties(m);};
$('#editSave').onclick=()=>$('#save').click();$('#editUndo').onclick=()=>travel(-1);$('#previousSection').onclick=()=>navigateSection(-1);$('#nextSection').onclick=()=>navigateSection(1);$('#sectionJump').onchange=e=>selectSection(e.target.value);$('#scrollCanvasUp').onclick=()=>canvasScroll(-1);$('#scrollCanvasDown').onclick=()=>canvasScroll(1);
$('#fullPageView').onclick=()=>openSection(sectionModels()[0]?.get('recipe').id);$('#boardHome').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('#boardTop').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
window.addEventListener('resize',positionTools);document.addEventListener('keydown',e=>{if(!$('#editDialog').open||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='PageDown'||e.key==='PageUp'){e.preventDefault();canvasScroll(e.key==='PageDown'?1:-1);}});
if(state&&canvasMain){buildBoard();bindCanvasWorkspace();editor.on('load',bindCanvasWorkspace);}
