(()=>{const btn=document.getElementById('analyzeImportBtn'),msgBox=document.getElementById('analyzeImportMsg'),out=document.getElementById('analyzeImportResult');if(btn&&out){const h=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));btn.onclick=async()=>{btn.disabled=true;msgBox.textContent='Разбираю таблицы и сопоставляю изображения…';msgBox.className='msg muted';out.innerHTML='';try{const r=await fetch('../api/import-analyze.php',{cache:'no-store',credentials:'same-origin'});const j=await r.json().catch(()=>({error:'bad_json'}));if(!r.ok||!j.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));if(j.kind==='diafan_1c_source'){
  const n=v=>Number(v||0).toLocaleString('ru-RU'),st=j.stats||{};
  msgBox.textContent='Проверка исходной выгрузки завершена. Данные не изменены.';msgBox.className='msg ok';
  out.innerHTML='<p><b>'+h(j.file)+'</b></p><p class="muted">Проверены CSV и файлы на сервере. Это не аудит связей в MySQL и не запуск импорта.</p>';
  const style=document.createElement('style');style.textContent='#analyzeImportResult .analysisGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:12px 0}#analyzeImportResult .analysisGrid>div{padding:12px;border:1px solid #e3e3df;border-radius:12px;background:#fff;min-width:0}#analyzeImportResult .analysisGrid b{display:block;font-size:23px}#analyzeImportResult .analysisGrid span{display:block;font-size:13px;overflow-wrap:anywhere}#analyzeImportResult .analysisSample{padding:10px 0;border-bottom:1px solid #e3e3df;overflow-wrap:anywhere}';out.appendChild(style);
  const metrics=[
    [j.image_files,'фотографий на сервере'],[st.valid_rows,'корректных записей CSV'],
    [st.rows_with_exact_photo,'записей с точным совпадением файла'],[st.rows_with_placeholder,'записей с заглушкой вместо фото'],
    [st.rows_with_ambiguous_photo,'записей с неоднозначным именем фото'],[st.rows_with_missing_photo,'записей с отсутствующей или недопустимой ссылкой'],
    [st.malformed_rows,'повреждённых записей CSV'],[Object.keys(j.duplicate_source_ids||{}).length,'повторяющихся кодов товара']
  ];
  const grid=document.createElement('div');grid.className='analysisGrid';
  grid.innerHTML=metrics.map(([v,label])=>'<div><b>'+n(v)+'</b><span>'+label+'</span></div>').join('');out.appendChild(grid);
  if(st.malformed_rows||Object.keys(j.duplicate_source_ids||{}).length){const warning=document.createElement('p');warning.textContent='Перед полным импортом нужно проверить повреждённые записи и повторяющиеся коды: они могут влиять на цены и остатки.';out.appendChild(warning);}
  for(const x of j.examples||[]){const d=document.createElement('div');d.className='analysisSample';const title=document.createElement('b');title.textContent=x.name+' · код '+x.source_id;const detail=document.createElement('div');detail.className='muted';detail.textContent=x.paths.length?x.paths.join(' / '):'Файл по исходной ссылке не найден.';d.appendChild(title);d.appendChild(detail);out.appendChild(d);}
  return;
}msgBox.textContent='Анализ завершён.';msgBox.className='msg ok';out.innerHTML=`<div class="analysisGrid"><div><b>${Number(j.tables?.length||0).toLocaleString('ru-RU')}</b><span>таблиц разобрано</span></div><div><b>${Number(j.rows||0).toLocaleString('ru-RU')}</b><span>строк товаров</span></div><div><b>${Number(j.matched_rows||0).toLocaleString('ru-RU')}</b><span>строк с фото</span></div><div><b>${Number(j.image_files||0).toLocaleString('ru-RU')}</b><span>изображений в индексе</span></div></div>`;for(const t of(j.tables||[])){const d=document.createElement('div');d.className='analysisTable';const fields=Object.keys(t.mapping||{}).join(', ')||'поля не распознаны';const imgCols=(t.image_columns||[]).join(', ')||'явных колонок фото нет';d.innerHTML=`<b>${h(t.file)}</b><div class="muted">Строк: ${Number(t.rows||0).toLocaleString('ru-RU')} · поля: ${h(fields)}</div><div class="muted">Фото-колонки: ${h(imgCols)} · прямых совпадений: ${Number(t.direct_matches||0).toLocaleString('ru-RU')} · по идентификатору: ${Number(t.identifier_matches||0).toLocaleString('ru-RU')}</div>`;out.appendChild(d)}if((j.samples||[]).length){const title=document.createElement('h3');title.textContent='Примеры найденных связей';out.appendChild(title);for(const s of j.samples.slice(0,8)){const d=document.createElement('div');d.className='analysisSample';d.innerHTML=`<b>${h(s.title||s.sku||'Товар')}</b><div class="muted">${h((s.images||[]).join(', '))}</div>`;out.appendChild(d)}}}catch(e){msgBox.textContent='Ошибка анализа: '+e.message;msgBox.className='msg err'}finally{btn.disabled=false}}}const s=document.createElement('script');s.src='import-apply.js?v=4';s.defer=true;document.head.appendChild(s)})();