<?php require __DIR__.'/guard.php'; ?>
<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Клиенты — ПрофиСпорт</title>
<style>
:root{--y:#f2c94c;--bg:#f5f5f3;--tx:#202124;--muted:#747a80;--line:#e3e3df;--green:#19964a;--red:#b93429;--page:1040px}*{box-sizing:border-box}body{margin:0;font:15px/1.4 system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif;background:var(--bg);color:var(--tx)}.top{background:linear-gradient(135deg,#454b51,#2f3439);color:#fff;position:sticky;top:0;z-index:20}.topin{max-width:var(--page);margin:auto;min-height:64px;padding:0 14px;display:flex;align-items:center;justify-content:space-between}.brand{font-weight:900;font-size:21px}.brand i{font-style:normal;color:var(--y)}.back{color:#fff;text-decoration:none;background:#ffffff17;border:1px solid #ffffff26;padding:10px 13px;border-radius:10px}main{max-width:var(--page);margin:18px auto;padding:0 14px 60px}.summary{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0 16px}.stat{background:#fff;border:1px solid var(--line);border-radius:14px;padding:11px 14px}.stat b{font-size:22px}.tools{display:grid;grid-template-columns:minmax(0,1fr) auto auto auto;gap:8px;margin:12px 0}.tools input{padding:11px;border:1px solid var(--line);border-radius:10px}.tools button,.tools a,.client button{border:0;border-radius:10px;padding:11px 14px;font-weight:800;background:var(--y);color:#111;text-decoration:none;text-align:center}.tools a{background:#e8e9e6}.client{background:#fff;border:1px solid var(--line);border-radius:16px;padding:16px;margin:12px 0}.client h3{margin:0 0 4px}.meta{color:var(--muted);font-size:13px;overflow-wrap:anywhere}.metrics{display:flex;gap:8px;flex-wrap:wrap;margin:9px 0}.pill{background:#f5f5f2;border-radius:999px;padding:6px 9px;font-size:12px}.pill.qr{background:#fff3b9}.bonus{font-size:22px;font-weight:900}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.actions input{padding:10px;border:1px solid var(--line);border-radius:9px}.amount{width:120px}.note{min-width:220px;flex:1}.ok{color:var(--green)}.err{color:var(--red)}
@media(max-width:600px){.tools{grid-template-columns:1fr 1fr}.tools input{grid-column:1/-1}.actions{display:grid;grid-template-columns:1fr 1fr}.actions .note{grid-column:1/-1;width:100%;min-width:0}.actions button{grid-column:1/-1}}
</style></head><body><header class="top"><div class="topin"><div class="brand">Профи<i>Спорт</i></div><a class="back" href="index.php">← Админка</a></div></header>
<main><h1>Клиентская база</h1><div id="summary" class="summary"></div><div class="tools"><input id="q" placeholder="Имя, фамилия, email или телефон"><button id="search">Найти</button><a id="export" href="../api/customer-admin.php?export=csv">Скачать CSV</a><a href="customer-qr.php">QR для печати</a></div><div id="list"></div></main>
<script>
let csrf='';const $=s=>document.querySelector(s),esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function auth(){const r=await fetch('../server/api.php?action=me',{cache:'no-store'});if(!r.ok){location.href='index.php';return false}const j=await r.json();csrf=j.csrf||'';return true}
function sourceName(value){return value==='store_qr'?'QR в магазине':value==='qr_and_account'?'QR + кабинет':'Сайт'}
async function load(){const u=new URL('../api/customer-admin.php',location.href);if(q.value.trim())u.searchParams.set('q',q.value.trim());const r=await fetch(u,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok){summary.textContent='Не удалось загрузить клиентов.';return}summary.innerHTML=`<div class="stat"><b>${Number(j.total||0).toLocaleString('ru-RU')}</b><br>всего клиентов</div><div class="stat"><b>${Number(j.qr_total||0).toLocaleString('ru-RU')}</b><br>через QR-код</div><div class="stat"><b>${j.loyalty?.enabled?'Включена':'Выключена'}</b><br>бонусная программа</div>`;const exportUrl=new URL('../api/customer-admin.php',location.href);exportUrl.searchParams.set('export','csv');if(q.value.trim())exportUrl.searchParams.set('q',q.value.trim());$('#export').href=exportUrl;list.innerHTML=j.items.map(x=>`<article class="client" data-id="${x.id}"><h3>${esc([x.name,x.last_name].filter(Boolean).join(' '))}</h3><div class="meta">${esc(x.phone||'Телефон не указан')} · ${esc(x.email)}${x.birth_date?` · ${esc(new Date(x.birth_date+'T00:00:00').toLocaleDateString('ru-RU'))}`:''}</div><div class="metrics"><span class="pill ${x.qr_registered_at?'qr':''}">${esc(sourceName(x.registration_source))}</span><span class="pill">${Number(x.has_account)?'Есть личный кабинет':'Анкета без кабинета'}</span><span class="pill">Заказов: ${x.orders_count}</span><span class="pill">Избранное: ${x.favorites_count}</span></div><div class="bonus">${Number(x.bonus_balance||0).toLocaleString('ru-RU')} бонусов</div><div class="meta">Служебный баланс. Автоматическая бонусная программа сейчас выключена.</div><div class="actions"><input class="amount" type="number" placeholder="+/- бонусы"><input class="note" placeholder="Причина корректировки"><button class="apply">Применить</button></div><div class="msg"></div></article>`).join('')||'<p>Клиентов пока нет.</p>';document.querySelectorAll('.client').forEach(c=>c.querySelector('.apply').onclick=()=>adjust(c))}
async function adjust(card){const amount=Number(card.querySelector('.amount').value||0),note=card.querySelector('.note').value.trim(),msg=card.querySelector('.msg');if(!amount){msg.textContent='Укажите сумму.';return}const r=await fetch('../api/customer-admin.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({customer_id:Number(card.dataset.id),amount,note})}),j=await r.json();if(!r.ok||!j.ok){msg.innerHTML='<span class="err">Не удалось изменить баланс.</span>';return}msg.innerHTML='<span class="ok">Баланс обновлён.</span>';setTimeout(load,300)}
search.onclick=load;q.addEventListener('keydown',e=>{if(e.key==='Enter')load()});(async()=>{if(await auth())load()})()
</script></body></html>
