(()=>{'use strict';const $=s=>document.querySelector(s);let state,fields,csrf='',selected='',busy=false,dirty=false,sellerDirty=false;
function message(text,error=false){$('#legalStatus').textContent=text;$('#legalStatus').dataset.error=String(error)}
function locks(value){busy=value;document.querySelectorAll('button').forEach(b=>b.disabled=value)}
function expand(text){return text.replace(/\{\{([a-z_]+)\}\}/g,(m,k)=>state.seller[k]||m)}
function documentPayload(action){return{action,slug:selected,title:$('#documentTitle').value,body:$('#documentBody').value}}
async function write(payload){if(busy)return;locks(true);try{const r=await fetch('../api/legal-admin.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({...payload,revision:state.revision})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.message||'Не удалось сохранить.');state=j.state;if(payload.action==='seller'){sellerDirty=false}else{dirty=false;show(selected)}renderList();message(payload.action==='publish'?'Документ опубликован.':payload.action==='unpublish'?'Документ снят с публикации.':payload.action==='restore'?'Редакция восстановлена в черновик.':'Изменения сохранены.');}catch(e){message(e.message,true)}finally{locks(false)}}
function renderSeller(){const box=$('#sellerFields');box.replaceChildren();for(const[key,label]of Object.entries(fields)){const l=document.createElement('label');l.textContent=label;const input=key==='seller_type'?document.createElement('select'):document.createElement('input');input.name=key;if(key==='seller_type'){for(const v of['','ИП','ООО']){const o=document.createElement('option');o.value=v;o.textContent=v||'Выберите форму';input.append(o)}}else{input.maxLength=2000;if(key==='email')input.type='email'}input.value=state.seller[key]||'';l.append(input);box.append(l)}}
function renderList(){const box=$('#documentList');box.replaceChildren();for(const d of Object.values(state.documents)){const b=document.createElement('button');b.type='button';b.setAttribute('aria-pressed',String(d.slug===selected));b.textContent=d.title;const small=document.createElement('small');small.textContent=d.published?'Опубликован · версия '+d.published.version:'Черновик · не виден покупателям';b.append(small);b.onclick=()=>{if(dirty&&!confirm('Перейти к другому документу без сохранения правок?'))return;show(d.slug);renderList();message('Редактируйте текст и сохраните черновик либо опубликуйте готовую редакцию.');};box.append(b)}}
function show(slug){selected=slug;dirty=false;const d=state.documents[slug];$('#editor').hidden=false;$('#editorHeading').textContent=d.title;$('#documentTitle').value=d.title;$('#documentBody').value=d.body;$('#documentNote').textContent=d.note||'';$('#documentNote').hidden=!d.note;$('#publishedInfo').textContent=d.published?'На сайте: версия '+d.published.version+' от '+d.published.published_at.slice(0,10)+'. Сохранение черновика не меняет эту редакцию.':'Документ пока не опубликован.';$('#unpublishButton').hidden=!d.published;$('#publicLink').hidden=!d.published;$('#publicLink').href='../legal.php?document='+encodeURIComponent(slug);$('#documentPreview').hidden=true;const history=$('#historyList');history.replaceChildren();if(!d.history.length)history.textContent='Предыдущих редакций пока нет.';for(const old of[...d.history].reverse()){const b=document.createElement('button');b.type='button';b.textContent='Версия '+old.version+' · '+old.published_at.slice(0,10)+' → восстановить в черновик';b.onclick=()=>{if(dirty&&!confirm('Заменить несохранённые правки предыдущей редакцией?'))return;write({action:'restore',slug:selected,version:old.version})};history.append(b)}}
$('#sellerForm').oninput=()=>{sellerDirty=true};$('#sellerForm').onsubmit=e=>{e.preventDefault();write({action:'seller',seller:Object.fromEntries(new FormData(e.currentTarget))})};$('#documentForm').onsubmit=e=>{e.preventDefault();write(documentPayload('save'))};$('#documentForm').oninput=()=>{dirty=true};$('#previewButton').onclick=()=>{const p=$('#documentPreview');p.textContent=$('#documentTitle').value+'\n\n'+expand($('#documentBody').value);p.hidden=false};$('#publishButton').onclick=()=>{if($('#documentForm').reportValidity())write(documentPayload('publish'))};$('#unpublishButton').onclick=()=>write({action:'unpublish',slug:selected});window.addEventListener('beforeunload',e=>{if(dirty||sellerDirty){e.preventDefault();e.returnValue=''}});
(async()=>{locks(true);try{const r=await fetch('../api/legal-admin.php',{cache:'no-store'});if(r.status===401){location.href='login.php';return}const j=await r.json();if(!r.ok||!j.ok)throw Error('Не удалось загрузить документы. Обновите страницу.');state=j.state;fields=j.fields;csrf=j.csrf;renderSeller();selected=Object.keys(state.documents)[0];renderList();show(selected);message('Подготовлено документов: '+Object.keys(state.documents).length+'. Сначала заполните реквизиты продавца.')}catch(e){message(e.message,true)}finally{locks(false)}})();
})();
