(()=>{
const $=id=>document.getElementById(id),form=$('migrationForm'),msg=$('migrationMessage'),jobs=$('migrationJobs');let csrf='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const errors={current_password_invalid:'Неверный текущий пароль.',owner_required:'Перенос доступен только владельцу.',target_database_not_empty:'Целевая база не пустая. Для безопасного переноса укажите пустую базу.',target_ftps_connect_failed:'Не удалось подключиться к FTPS-серверу.',target_ftps_login_failed:'Неверный FTPS-логин или пароль.',target_ftps_write_failed:'Нет права записи в папку нового сайта.',target_db_credentials_required:'Заполните реквизиты новой базы.',target_url_https_required:'Адрес нового сайта должен начинаться с https://',migration_already_active:'Уже есть активное задание переноса.',ftps_unavailable_on_current_host:'На текущем хостинге недоступен FTPS-клиент. Автоперенос с этого сервера невозможен.'};
async function json(url,opt={}){const r=await fetch(url,{cache:'no-store',...opt});const j=await r.json().catch(()=>({error:'bad_json'}));if(!r.ok)throw new Error(errors[j.error]||j.error||('HTTP '+r.status));return j}
async function auth(){const j=await json('../server/api.php?action=me');csrf=j.csrf||''}
function payload(includePassword=true){const v=Object.fromEntries(new FormData(form));if(!includePassword)delete v.current_password;return v}
async function call(action,data){return json('../api/migration.php?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)})}
function phase(x){return({db_schema:'Структура базы',db_data:'Данные',files:'Файлы',config:'Конфигурация',verify:'Проверка',completed:'Завершено'})[x]||x}
function status(x){return({scheduled:'Запланирован',running:'Выполняется',completed:'Завершён',failed:'Ошибка',cancelled:'Отменён'})[x]||x}
async function load(){
 const j=await json('../api/migration.php?action=status');const list=j.items||[];
 jobs.innerHTML=list.length?list.map(x=>{const p=x.progress||{};return '<div class="job"><div><span class="pill">'+esc(status(x.status))+'</span> · <b>#'+x.id+'</b></div><div>'+esc(phase(x.phase))+' · запуск '+esc(x.due_at)+'</div><div class="muted">Таблиц: '+Number(p.data_tables||p.schema_tables||0)+' · строк: '+Number(p.rows_copied||0)+' · файлов: '+Number(p.files_copied||0)+'</div>'+(x.error?'<p class="bad">'+esc(x.error)+'</p>':'')+(x.status==='scheduled'?'<button class="btn danger" data-cancel="'+x.id+'" type="button">Отменить</button>':'')+'</div>'}).join(''):'<p class="muted">Заданий переноса пока нет.</p>';
 jobs.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{const password=prompt('Введите текущий пароль админки для отмены переноса');if(!password)return;b.disabled=true;try{await call('cancel',{id:Number(b.dataset.cancel),current_password:password});await load()}catch(e){alert(e.message)}finally{b.disabled=false}});
}
$('preflightBtn').onclick=async()=>{const b=$('preflightBtn');b.disabled=true;msg.className='muted';msg.textContent='Проверяем новый сервер…';try{const j=await call('preflight',payload(false));msg.className='ok';msg.textContent='Проверка пройдена: FTPS работает, MySQL доступен, база пустая.';}catch(e){msg.className='bad';msg.textContent=e.message}finally{b.disabled=false}};
form.onsubmit=async e=>{e.preventDefault();const password=form.elements.current_password.value;if(!password){msg.className='bad';msg.textContent='Введите текущий пароль для подтверждения.';return}if(!confirm('Запланировать полный перенос файлов и базы на новый сервер? До запуска его можно отменить.'))return;const b=e.submitter;b.disabled=true;msg.className='muted';msg.textContent='Повторно проверяем сервер и создаём задание…';try{const j=await call('schedule',payload(true));msg.className='ok';msg.textContent='Перенос запланирован на '+j.due_at+'. Пароль подтверждён.';form.elements.current_password.value='';await load()}catch(e){msg.className='bad';msg.textContent=e.message}finally{b.disabled=false}};
$('refreshMigration').onclick=load;
(async()=>{try{await auth();await load()}catch(e){msg.className='bad';msg.textContent=e.message}})();
})();