(()=>{
const $=id=>document.getElementById(id),labels={new:'Новый',confirmed:'Подтверждён',processing:'В работе',ready:'Готов к выдаче',completed:'Завершён',cancelled:'Отменён'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rub=n=>Number(n).toLocaleString('ru-RU')+' ₽';let page=1,csrf='',current=null;
async function api(query,options={}){const r=await fetch('../api/orders.php?'+query,{cache:'no-store',...options});const j=await r.json();if(r.status===401){location.href='login.php';throw Error('Войдите в систему.')}if(!r.ok)throw Error(j.error==='order_changed'?'Заказ уже изменён другим сотрудником. Откройте его повторно.':'Не удалось выполнить действие.');return j}
async function load(){try{$('message').textContent='Загрузка…';const params=new URLSearchParams(new FormData($('filters')));params.set('page',page);const j=await api(params);$('orders').innerHTML=j.items.map(o=>`<article class="orderCard"><b>${esc(o.order_number)}</b> · ${esc(labels[o.status]||o.status)}<p>${esc(o.customer_name)} · ${esc(o.phone)}</p><p>${esc(o.created_at)} · <b>${rub(o.total_rub)}</b></p><button data-order="${o.id}">Открыть заказ</button></article>`).join('')||'<p>Заказов не найдено.</p>';$('pageInfo').textContent=`${j.page} / ${j.pages} · Всего ${j.total}`;$('prev').disabled=page<=1;$('next').disabled=page>=j.pages;$('message').textContent='';document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>open(b.dataset.order))}catch(e){$('message').textContent=e.message}}
function historyMarkup(list){return '<div class="statusHistory"><h3>История статусов</h3>'+((list||[]).map(function(h){return '<div class="statusHistoryRow"><span>'+esc(labels[h.status]||h.status)+'</span><small>'+esc(h.created_at||'')+'</small></div>'}).join('')||'<p>История пока пуста.</p>')+'</div>'}
async function open(id){try{const j=await api('id='+encodeURIComponent(id));current=j.order;const o=current;const delivery=o.delivery_method==='pickup'?'Самовывоз · '+esc(o.pickup_store||'Проспект Победы, 79'):'Доставка по Оренбургу'+(o.address?' · '+esc(o.address):'');$('details').innerHTML='<h2>'+esc(o.order_number)+'</h2><p>'+esc(o.customer_name)+'<br>'+esc(o.phone)+'<br>'+esc(o.email||'')+'</p><p>'+delivery+'</p><p id="detailComment">'+esc(o.comment||'')+'</p>'+j.items.map(function(i){return '<div class="item"><span>'+esc(i.title)+' × '+i.quantity+'</span><b>'+rub(i.line_total_rub)+'</b></div>'}).join('')+'<h3>Итого: '+rub(o.total_rub)+'</h3>'+historyMarkup(j.history)+'<label>Статус <select id="orderStatus">'+Object.entries(labels).map(function(x){return '<option value="'+x[0]+'" '+(o.status===x[0]?'selected':'')+'>'+x[1]+'</option>'}).join('')+'</select></label> <button id="saveStatus">Сохранить статус</button>';$('detailMessage').textContent='';$('saveStatus').onclick=saveStatus;$('detail').showModal()}catch(e){$('message').textContent=e.message}}
async function saveStatus(){const b=$('saveStatus');b.disabled=true;try{await api('',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({id:current.id,status:$('orderStatus').value,previous_status:current.status})});current.status=$('orderStatus').value;$('detailMessage').textContent='Статус сохранён.';await load()}catch(e){$('detailMessage').textContent=e.message}finally{b.disabled=false}}
$('closeDetail').onclick=()=>$('detail').close();$('filters').onsubmit=e=>{e.preventDefault();page=1;load()};$('prev').onclick=()=>{page--;load()};$('next').onclick=()=>{page++;load()};
(async()=>{try{const r=await fetch('../server/api.php?action=me',{cache:'no-store'});if(!r.ok){location.href='login.php';return}const j=await r.json();csrf=j.csrf;await load()}catch(e){$('message').textContent='Не удалось подключиться. Обновите страницу.'}})();
})();
