(()=>{
const $=id=>document.getElementById(id),labels={new:'Новый',confirmed:'Подтверждён',ready:'Готов к выдаче',completed:'Завершён',cancelled:'Отменён'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rub=n=>Number(n).toLocaleString('ru-RU')+' ₽';let page=1,csrf='',current=null;
async function api(query,options={}){const r=await fetch('../api/orders.php?'+query,{cache:'no-store',...options});const j=await r.json();if(r.status===401){location.href='login.php';throw Error('Войдите в систему.')}if(!r.ok)throw Error(j.error==='order_changed'?'Заказ уже изменён другим сотрудником. Откройте его повторно.':'Не удалось выполнить действие.');return j}
async function load(){try{$('message').textContent='Загрузка…';const params=new URLSearchParams(new FormData($('filters')));params.set('page',page);const j=await api(params);$('orders').innerHTML=j.items.map(o=>`<article class="orderCard"><b>${esc(o.order_number)}</b> · ${esc(labels[o.status]||o.status)}<p>${esc(o.customer_name)} · ${esc(o.phone)}</p><p>${esc(o.created_at)} · <b>${rub(o.total_rub)}</b></p><button data-order="${o.id}">Открыть заказ</button></article>`).join('')||'<p>Заказов не найдено.</p>';$('pageInfo').textContent=`${j.page} / ${j.pages} · Всего ${j.total}`;$('prev').disabled=page<=1;$('next').disabled=page>=j.pages;$('message').textContent='';document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>open(b.dataset.order))}catch(e){$('message').textContent=e.message}}
async function open(id){try{const j=await api('id='+encodeURIComponent(id));current=j.order;const o=current;$('details').innerHTML=`<h2>${esc(o.order_number)}</h2><p>${esc(o.customer_name)}<br>${esc(o.phone)}<br>${esc(o.email||'')}</p><p>${o.delivery_method==='pickup'?'Самовывоз':'Доставка по Оренбургу'}<br>${esc(o.address||'')}</p><p id="detailComment">${esc(o.comment||'')}</p>${j.items.map(i=>`<div class="item"><span>${esc(i.title)} × ${i.quantity}</span><b>${rub(i.line_total_rub)}</b></div>`).join('')}<h3>Итого: ${rub(o.total_rub)}</h3><label>Статус <select id="orderStatus">${Object.entries(labels).map(([v,t])=>`<option value="${v}" ${o.status===v?'selected':''}>${t}</option>`).join('')}</select></label> <button id="saveStatus">Сохранить статус</button>`;$('detailMessage').textContent='';$('saveStatus').onclick=saveStatus;$('detail').showModal()}catch(e){$('message').textContent=e.message}}
async function saveStatus(){const b=$('saveStatus');b.disabled=true;try{await api('',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({id:current.id,status:$('orderStatus').value,previous_status:current.status})});current.status=$('orderStatus').value;$('detailMessage').textContent='Статус сохранён.';await load()}catch(e){$('detailMessage').textContent=e.message}finally{b.disabled=false}}
$('closeDetail').onclick=()=>$('detail').close();$('filters').onsubmit=e=>{e.preventDefault();page=1;load()};$('prev').onclick=()=>{page--;load()};$('next').onclick=()=>{page++;load()};
(async()=>{try{const r=await fetch('../server/api.php?action=me',{cache:'no-store'});if(!r.ok){location.href='login.php';return}const j=await r.json();csrf=j.csrf;await load()}catch(e){$('message').textContent='Не удалось подключиться. Обновите страницу.'}})();
})();
