<?php require __DIR__.'/guard.php'; ?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Заказы — ПрофиСпорт</title><link rel="stylesheet" href="../styles.css"><style>main{max-width:1100px;padding:20px;margin:auto}.tools{display:flex;gap:12px;flex-wrap:wrap}.tools input,.tools select{padding:12px;font:inherit;max-width:100%}.orderCard{padding:18px;border:1px solid #ddd;background:white;border-radius:14px;margin:12px 0}.orderCard button{margin-top:12px}dialog{width:min(640px,90vw);max-height:85vh;overflow:auto;border:0;border-radius:16px;padding:24px}dialog::backdrop{background:#0007}.item{display:flex;justify-content:space-between;gap:16px;padding:12px 0;border-bottom:1px solid #ddd}#details{white-space:normal;overflow-wrap:anywhere}#message{color:#a21e15}select{font:inherit;padding:10px}button,a{min-height:44px}#detailComment{white-space:pre-wrap}.statusHistory{margin:18px 0;padding:14px;border-radius:12px;background:#f6f6f2}.statusHistory h3{margin:0 0 8px}.statusHistoryRow{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-top:1px solid #e5e5df}.statusHistoryRow:first-of-type{border-top:0}/* Keep full-width controls out of inline label line boxes. */
#detail{max-height:calc(100dvh - 32px);max-width:calc(100vw - 32px)}
#details>label{display:grid;gap:8px;margin-top:20px;line-height:1.5}
#orderStatus{display:block;width:100%;min-height:44px;margin:0}
#saveStatus{display:block;margin-top:14px;max-width:100%;white-space:normal}
#detailMessage{margin:14px 0 0;line-height:1.5;overflow-wrap:anywhere}
#detailMessage:empty{display:none}
#details>.item{align-items:flex-start}
#details>.item>span{flex:1;min-width:0;line-height:1.5}
#details>.item>b{flex:none;white-space:nowrap;line-height:1.5}
.statusHistoryRow{flex-wrap:wrap;line-height:1.5}
.tools>input{flex:1 1 240px;width:auto}
.tools>select{flex:1 1 180px;width:auto}
@media(max-width:480px){#detail{padding:18px}#details>.item{flex-direction:column;gap:6px}#saveStatus{width:100%}}
</style><link rel="stylesheet" href="../motion.css?v=1"><style>@view-transition{navigation:none}</style><link rel="stylesheet" href="layout.css?v=2"></head><body class="motion-page motion-admin"><main><a href="index.php">← Управление магазином</a><h1>Заказы</h1><p class="adminPageHelp">Найдите заказ по номеру или покупателю. Откройте его карточку, чтобы посмотреть состав, контакты и изменить статус.</p><form id="filters" class="tools"><input name="q" aria-label="Поиск заказов" placeholder="Номер, имя или телефон"><select name="status" aria-label="Статус"><option value="">Все статусы</option><option value="new">Новый</option><option value="confirmed">Подтверждён</option><option value="processing">В работе</option><option value="ready">Готов к выдаче</option><option value="completed">Завершён</option><option value="cancelled">Отменён</option></select><button>Найти</button></form><p id="message" role="status"></p><div id="orders"></div><div class="tools"><button id="prev">Назад</button><span id="pageInfo"></span><button id="next">Далее</button></div><dialog id="detail"><button id="closeDetail">Закрыть</button><div id="details"></div><p id="detailMessage" role="status"></p></dialog></main><script src="orders.js?v=2"></script><?php require __DIR__.'/menu.php'; ?></body></html>
