<?php require __DIR__.'/guard.php'; ?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Отзывы — ПрофиСпорт</title><style>:root{--y:#f2c94c;--bg:#f5f5f3;--tx:#202124;--muted:#747a80;--line:#e3e3df;--green:#19964a;--red:#b93429;--page:1040px}*{box-sizing:border-box}body{margin:0;font:15px/1.4 system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif;background:var(--bg);color:var(--tx)}.top{background:linear-gradient(135deg,#454b51,#2f3439);color:#fff;position:sticky;top:0}.topin{max-width:var(--page);margin:auto;min-height:64px;padding:0 14px;display:flex;align-items:center;justify-content:space-between}.brand{font-weight:900;font-size:21px}.brand i{font-style:normal;color:var(--y)}.back{color:#fff;text-decoration:none;background:#ffffff17;border:1px solid #ffffff26;padding:10px 13px;border-radius:10px}main{max-width:var(--page);margin:18px auto;padding:0 14px 60px}.tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.tools button,.review button{border:0;border-radius:10px;padding:11px 14px;font-weight:800;background:var(--y)}.tools .secondary,.review .secondary{background:#e9e9e5}.review{background:#fff;border:1px solid var(--line);border-radius:16px;padding:16px;margin:12px 0}.review h3{margin:0 0 4px}.meta{color:var(--muted);font-size:13px}.stars{color:#d2a600;font-size:18px}.actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:12px}.actions input{width:130px;padding:10px;border:1px solid var(--line);border-radius:9px}.ok{color:var(--green)}.err{color:var(--red)}.empty{background:#fff;border:1px solid var(--line);border-radius:16px;padding:22px}.activeTab{background:#454b51!important;color:#fff!important}.rejectionForm{display:grid;gap:10px;margin-top:12px;padding:14px;background:#f5f5f3;border-radius:10px}.rejectionForm[hidden]{display:none}.rejectionForm label{display:grid;gap:6px}.rejectionForm select,.rejectionForm textarea{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;font:inherit}.archiveReason{padding:12px;background:#f7efed;border-radius:10px}.archiveReason p{white-space:pre-wrap}.review>p{white-space:pre-wrap}.tools button:disabled{opacity:.5}</style><link rel="stylesheet" href="../motion.css?v=1"><style>@view-transition{navigation:none}</style><link rel="stylesheet" href="layout.css?v=1"></head><body class="motion-page motion-admin"><header class="top"><div class="topin"><div class="brand">Профи<i>Спорт</i></div><a class="back" href="index.php">← Админка</a></div></header><main><h1>Отзывы</h1><div class="tools"><button data-status="pending" class="activeTab">На модерации</button><button data-status="approved" class="secondary">Опубликованные</button><button data-status="rejected" class="secondary">Архив отклонённых</button></div><div id="summary"></div><div id="list"></div><div id="pagination" class="tools"></div></main><script>let csrf='',status='pending',page=1,pages=1,reasons={},requestSequence=0;
const $=s=>document.querySelector(s),esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function auth(){const r=await fetch('../server/api.php?action=me',{cache:'no-store'});if(!r.ok){location.href='index.php';return false}const j=await r.json();csrf=j.csrf||'';return true}
async function load(){
 const sequence=++requestSequence;$('#summary').textContent='Загрузка…';
 try{
  const r=await fetch('../api/review-moderation.php?status='+status+'&page='+page,{cache:'no-store'}),j=await r.json();if(sequence!==requestSequence)return;if(!r.ok||!j.ok)throw Error();
  reasons=j.rejection_reasons||{};page=j.page;pages=j.pages;
  $('#summary').textContent=(status==='rejected'?'В архиве: ':'Отзывов: ')+j.total;
  $('#list').innerHTML=j.items.length?j.items.map(x=>`<article class="review" data-id="${Number(x.id)}"><h3>${esc(x.product_name||'Товар')}</h3><div class="meta">${esc(x.customer_name||'Покупатель')} · ${esc(x.customer_email||'')} · ${esc(x.created_at||'')}</div><div class="stars">${'★'.repeat(Math.max(0,Math.min(5,Number(x.rating)||0)))}</div><p>${esc(x.review_text)}</p>${status==='rejected'?`<div class="archiveReason"><b>Причина: ${esc(reasons[x.rejection_reason_code]||'Не указана — отзыв отклонён ранее')}</b>${x.rejection_note?`<p>${esc(x.rejection_note)}</p>`:''}<div class="meta">${esc(x.rejected_at||'')}${x.rejected_by_name?' · '+esc(x.rejected_by_name):''}</div></div>`:''}${status==='pending'?`<div class="actions"><button class="approve">Опубликовать</button><button class="reject secondary">Отклонить</button></div><form class="rejectionForm" hidden><label>Причина отклонения<select name="reason_code" required><option value="">Выберите причину</option>${Object.entries(reasons).map(([code,label])=>`<option value="${esc(code)}">${esc(label)}</option>`).join('')}</select></label><label>Комментарий<textarea name="reason_note" rows="3" maxlength="500" placeholder="Пояснение для других модераторов"></textarea></label><small>Причина и комментарий доступны только сотрудникам.</small><div class="actions"><button type="submit">Отклонить и сохранить в архиве</button><button type="button" class="cancelReject secondary">Отмена</button></div></form>`:''}<div class="msg" role="status"></div></article>`).join(''):'<div class="empty">Здесь пока пусто.</div>';
  $('#pagination').innerHTML=pages>1?`<button id="previousPage" ${page<=1?'disabled':''}>Предыдущая страница</button><span>Страница ${page} из ${pages}</span><button id="nextPage" ${page>=pages?'disabled':''}>Следующая страница</button>`:'';
  $('#previousPage')?.addEventListener('click',()=>{page--;load()});$('#nextPage')?.addEventListener('click',()=>{page++;load()});bind();
 }catch(e){if(sequence===requestSequence)$('#summary').textContent='Не удалось загрузить отзывы. Попробуйте ещё раз.';}
}
function bind(){document.querySelectorAll('.review').forEach(card=>{
 card.querySelector('.approve')?.addEventListener('click',()=>moderate(card,'approve'));
 const form=card.querySelector('.rejectionForm');if(!form)return;
 card.querySelector('.reject').onclick=()=>{form.hidden=false;form.elements.reason_code.focus()};
 card.querySelector('.cancelReject').onclick=()=>{form.hidden=true;card.querySelector('.msg').textContent=''};
 form.elements.reason_code.onchange=()=>{form.elements.reason_note.required=form.elements.reason_code.value==='other';form.elements.reason_note.minLength=form.elements.reason_code.value==='other'?5:0};
 form.onsubmit=e=>{e.preventDefault();if(form.reportValidity())moderate(card,'reject',Object.fromEntries(new FormData(form)))};
})}
async function moderate(card,action,reason={}){
 const msg=card.querySelector('.msg'),controls=[...card.querySelectorAll('button,select,textarea')];if(controls.some(x=>x.disabled))return;
 controls.forEach(x=>x.disabled=true);msg.textContent='Сохраняю…';
 try{const r=await fetch('../api/review-moderation.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({review_id:Number(card.dataset.id),action,...reason})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error);msg.textContent=action==='reject'?'Отзыв сохранён в архиве.':'Отзыв опубликован.';await load();}
 catch(e){msg.textContent=e.message==='rejection_reason_required'?'Выберите причину; для «Другая причина» добавьте пояснение.':e.message==='already_moderated'?'Этот отзыв уже обработан. Обновите список.':'Не удалось сохранить. Попробуйте ещё раз.';controls.forEach(x=>x.disabled=false);}
}
document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{status=b.dataset.status;page=1;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('activeTab',x===b));load()});
(async()=>{if(await auth())load()})();</script></body></html>