<?php
declare(strict_types=1);
require __DIR__.'/../server/bootstrap.php';
start_secure_session();
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
@set_time_limit(0);

function out(array $x,int $code=200): never { http_response_code($code); echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE); exit; }
function norm(string $s): string { return preg_replace('/[^a-zа-я0-9]+/u','',mb_strtolower(trim($s)))??''; }
function utf8(string $s): string { if(str_starts_with($s,"\xFF\xFE"))return mb_convert_encoding(substr($s,2),'UTF-8','UTF-16LE');if(str_starts_with($s,"\xFE\xFF"))return mb_convert_encoding(substr($s,2),'UTF-8','UTF-16BE');$e=mb_detect_encoding($s,['UTF-8','Windows-1251','CP1251'],true)?:'UTF-8'; return $e==='UTF-8'?$s:mb_convert_encoding($s,'UTF-8',$e); }
function csvAll(string $path): array { $raw=file_get_contents($path); if($raw===false)throw new RuntimeException('read_failed'); if(str_starts_with($raw,"\xEF\xBB\xBF"))$raw=substr($raw,3); $raw=utf8($raw); if(trim($raw)==='')throw new RuntimeException('csv_empty:'.basename($path));$first=preg_split('/\R/u',$raw,2)[0]??''; $c=[';'=>substr_count($first,';'),','=>substr_count($first,','),"\t"=>substr_count($first,"\t")]; arsort($c);$d=(string)array_key_first($c);$f=fopen('php://temp','r+');fwrite($f,$raw);rewind($f);$h=fgetcsv($f,0,$d)?:[];$rows=[];while(($r=fgetcsv($f,0,$d))!==false){if(count(array_filter($r,fn($v)=>trim((string)$v)!=='')))$rows[]=$r;}fclose($f);return[$h,$rows,$d]; }
function col(array $h,array $aliases): ?int { foreach($h as $i=>$v){$n=norm((string)$v);foreach($aliases as $a)if($n===norm($a))return $i;}return null; }
function val(array $r,?int $i): string { return $i===null?'':trim((string)($r[$i]??'')); }
function money(string $x): int { $x=preg_replace('/[^0-9,.-]/u','',$x)??'';$x=str_replace(',','.',$x);return is_numeric($x)?(int)round((float)$x):0; }
function inferTextCol(array $h,array $rows): ?int { if(!$rows)return null;$width=max(count($h),count($rows[0]??[]));$best=null;$score=-1;$sample=array_slice($rows,0,200);for($i=0;$i<$width;$i++){$good=0;$non=0;$u=[];foreach($sample as $r){$x=trim((string)($r[$i]??''));if($x==='')continue;$non++;$u[$x]=1;if(mb_strlen($x)>3&&!is_numeric(str_replace([' ','.',','],'',$x)))$good++;}if(!$non)continue;$s=($good/$non)+(count($u)/$non)*.2;if($s>$score){$score=$s;$best=$i;}}return $best; }
function authImport(array $config): void { $given=(string)($_SERVER['HTTP_X_IMPORT_TOKEN']??'');$expected=(string)($config['import_token']??'');if($expected!==''&&$given!==''&&hash_equals($expected,$given))return;require_admin();if($_SERVER['REQUEST_METHOD']==='POST')csrf_check(); }
function findCsvs(string $root): array { $products=[];$categories=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile()||mb_strtolower($f->getExtension())!=='csv')continue;$n=mb_strtolower($f->getFilename());$row=['path'=>$f->getPathname(),'size'=>$f->getSize(),'mtime'=>$f->getMTime()];if(str_contains($n,'tovary'))$products[]=$row;elseif(str_contains($n,'categor')||str_contains($n,'category'))$categories[]=$row;} $pick=function(array $a):?string{if(!$a)return null;usort($a,fn($x,$y)=>($y['size']<=>$x['size'])?:($y['mtime']<=>$x['mtime']));return $a[0]['size']>0?$a[0]['path']:null;};return[$pick($products),$pick($categories),$products,$categories]; }

try{
 authImport($config); if($_SERVER['REQUEST_METHOD']!=='POST')throw new RuntimeException('post_required');
 $root=realpath(__DIR__.'/../import');if(!$root)throw new RuntimeException('import_missing');[$productFile,$categoryFile,$productCandidates,$categoryCandidates]=findCsvs($root);if(!$productFile)throw new RuntimeException('products_csv_missing_or_empty');
 [$h,$rows,$delimiter]=csvAll($productFile);$total=count($rows);$offset=max(0,(int)($_GET['offset']??0));$limit=min(1000,max(100,(int)($_GET['limit']??500)));$slice=array_slice($rows,$offset,$limit);
 $id=col($h,['id','guid','uuid','код','код товара','ид','идентификатор','id товара','id элемента']);$sku=col($h,['sku','артикул','арт','vendorcode','article']);$barcode=col($h,['barcode','штрихкод','штрих код','ean']);$title=col($h,['name','title','наименование','название','товар','название товара']);if($title===null)$title=inferTextCol($h,$rows);$price=col($h,['price','цена','розничная цена','цена продажи','price_rub']);$cat=col($h,['category','категория','группа','cat_id','category_id','id категории','раздел']);
 if($title===null)out(['ok'=>false,'error'=>'title_column_missing','source'=>basename($productFile),'source_size'=>filesize($productFile),'delimiter'=>$delimiter,'headers'=>array_slice($h,0,30),'first_rows'=>array_slice($rows,0,3),'product_candidates'=>array_map(fn($x)=>['name'=>basename($x['path']),'size'=>$x['size']],$productCandidates)],422);
 $categories=[];if($categoryFile){[$ch,$cr]=csvAll($categoryFile);$cid=col($ch,['id','код','category_id','id категории']);$cn=col($ch,['name','title','наименование','название','категория']);$cp=col($ch,['parent_id','родитель','parent','id родителя']);if($cn===null)$cn=inferTextCol($ch,$cr);foreach($cr as $r){$key=val($r,$cid);$name=val($r,$cn);if($name==='')continue;if($key==='')$key=$name;$categories[$key]=['name'=>$name,'parent'=>val($r,$cp)];}}
 $catPath=function(string $key)use(&$categories):string{if($key===''||!isset($categories[$key]))return $key;$parts=[];$seen=[];while($key!==''&&isset($categories[$key])&&!isset($seen[$key])){$seen[$key]=1;array_unshift($parts,$categories[$key]['name']);$key=$categories[$key]['parent'];}return implode(' / ',$parts);};
 if($offset===0)$pdo->exec('UPDATE products SET is_active=0');
 $byHash=$pdo->prepare('SELECT id,images,specs,description,category_path FROM products WHERE source_hash=? LIMIT 1');$byTitle=$pdo->prepare('SELECT id,images,specs,description,category_path FROM products WHERE title=? ORDER BY is_active DESC,id DESC LIMIT 1');
 $ins=$pdo->prepare('INSERT INTO products(source_hash,title,price_rub,availability,category_path,specs,description,images,is_active) VALUES(?,?,?,?,?,?,?,?,1)');$upd=$pdo->prepare('UPDATE products SET source_hash=?,title=?,price_rub=?,availability=?,category_path=?,specs=?,description=?,images=?,is_active=1,updated_at=CURRENT_TIMESTAMP WHERE id=?');
 $created=0;$updated=0;$reusedImages=0;$pdo->beginTransaction();
 foreach($slice as $r){$t=val($r,$title);if($t==='')continue;$ident='';foreach([$id,$sku,$barcode] as $ci){$z=val($r,$ci);if($z!==''){$ident=$z;break;}}$hash=hash('sha256','1c|'.($ident!==''?$ident:json_encode($r,JSON_UNESCAPED_UNICODE)));$p=money(val($r,$price));$category=$catPath(val($r,$cat));
  $byHash->execute([$hash]);$existing=$byHash->fetch();if(!$existing){$byTitle->execute([$t]);$existing=$byTitle->fetch();}
  $images=$existing['images']??'[]';$specs=$existing['specs']??null;$desc=$existing['description']??null;if(($images??'[]')!=='[]')$reusedImages++;
  if($category===''&&$existing)$category=(string)($existing['category_path']??'');
  if($existing){$upd->execute([$hash,$t,$p,'available',$category,$specs,$desc,$images,(int)$existing['id']]);$updated++;}else{$ins->execute([$hash,$t,$p,'available',$category,$specs,$desc,$images]);$created++;}
 }
 $pdo->commit();$next=$offset+count($slice);$done=$next>=$total;
 if($done){$meta=['file'=>basename($productFile),'rows'=>$total,'finished_at'=>date('c'),'category_rows'=>count($categories)];$s=$pdo->prepare("INSERT INTO site_settings(setting_key,setting_value) VALUES('last_1c_import',?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");$s->execute([json_encode($meta,JSON_UNESCAPED_UNICODE)]);audit($pdo,'import_1c_complete','products',null,$meta);}
 out(['ok'=>true,'source'=>basename($productFile),'source_size'=>filesize($productFile),'category_source'=>$categoryFile?basename($categoryFile):null,'headers'=>$offset===0?$h:null,'detected'=>['id'=>$id,'sku'=>$sku,'barcode'=>$barcode,'title'=>$title,'price'=>$price,'category'=>$cat],'offset'=>$offset,'processed'=>count($slice),'total_rows'=>$total,'created'=>$created,'updated'=>$updated,'rows_reusing_existing_images'=>$reusedImages,'category_rows'=>count($categories),'next_offset'=>$next,'done'=>$done]);
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log($e->__toString());out(['ok'=>false,'error'=>$e->getMessage()],500);}
