<?php
declare(strict_types=1);
require __DIR__.'/../server/bootstrap.php';
start_secure_session();
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
@set_time_limit(0);
function out(array $x,int $code=200): never{http_response_code($code);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);exit;}
function utf8(string $s):string{if(str_starts_with($s,"\xEF\xBB\xBF"))return substr($s,3);if(str_starts_with($s,"\xFF\xFE"))return mb_convert_encoding(substr($s,2),'UTF-8','UTF-16LE');if(str_starts_with($s,"\xFE\xFF"))return mb_convert_encoding(substr($s,2),'UTF-8','UTF-16BE');return mb_check_encoding($s,'UTF-8')?$s:mb_convert_encoding($s,'UTF-8','Windows-1251');}
function csvRows(string $p):array{$raw=file_get_contents($p);if($raw===false)throw new RuntimeException('read_failed');$raw=str_replace("\0",'',utf8($raw));$rows=[];foreach(preg_split('/\r\n|\n|\r/',$raw)?:[] as $ln){if(trim($ln)==='')continue;$r=str_getcsv($ln,';','"','\\');if(count(array_filter($r,fn($v)=>trim((string)$v)!=='')))$rows[]=$r;}return $rows;}
function normHeader(string $s):string{return preg_replace('/[^a-zа-я0-9]+/u','',mb_strtolower(trim($s)))??'';}
function headerMap(array $row):array{$aliases=['source_id'=>['id','guid','uuid','код','кодтовара','ид','идентификатор'],'sku'=>['sku','артикул','арт','vendorcode'],'name'=>['name','title','наименование','название','товар'],'category'=>['category','категория','группа'],'price'=>['price','цена','розничнаяцена','ценарозница'],'stock'=>['stock','stockqty','qty','quantity','остаток','остатки','остатоксклад','остатокнаскладе','остатоктовара','остатоктоваров','количество','количествотовара','количествотоваров','количествонаскладе','остатокшт','остатокштук','вналичии'],'image'=>['image','images','photo','photos','picture','pictures','картинка','изображение','фото','фотографии','файлфото']];$map=[];foreach($row as $i=>$h){$n=normHeader((string)$h);foreach($aliases as $field=>$vals){foreach($vals as $a){if($n===normHeader($a)){$map[$field]=(int)$i;break 2;}}}}return $map;}
function stockQty(string $x):?int{$x=trim(str_replace(["\xc2\xa0",' '],'',$x));if($x==='')return null;$x=str_replace(',','.',$x);if(!preg_match('/^-?\d+(?:\.\d+)?$/u',$x))return null;return max(0,(int)floor((float)$x));}
function detectStockColumn(array $rows,array $excluded):?array{$sample=array_slice($rows,0,min(2500,count($rows)));$maxCols=0;foreach($sample as $r)$maxCols=max($maxCols,count($r));$try=[];for($i=11;$i<$maxCols;$i++)$try[]=$i;for($i=0;$i<$maxCols;$i++)if(!in_array($i,$try,true)&&!in_array($i,$excluded,true))$try[]=$i;$scores=[];foreach($try as $i){$nonblank=$numeric=$zero=$positive=$decimal=$large=0;$max=0;foreach($sample as $r){$raw=trim((string)($r[$i]??''));if($raw==='')continue;$nonblank++;$clean=str_replace(["\xc2\xa0",' ', ','],['','','.'],$raw);if(!preg_match('/^-?\d+(?:\.\d+)?$/u',$clean))continue;$numeric++;$v=(float)$clean;if(floor($v)!=$v)$decimal++;if($v<=0)$zero++;else$positive++;$max=max($max,$v);if($v>10000)$large++;}if($nonblank<max(30,(int)floor(count($sample)*.15)))continue;$coverage=$numeric/max(1,$nonblank);if($coverage<.95)continue;$score=$coverage*1000+$numeric+($i>=11?300:0)+min($zero,100)+min($positive,100)-$decimal*5-$large*20;if($max>1000000)$score-=1000;$scores[]=['index'=>$i,'score'=>$score,'coverage'=>$coverage,'numeric'=>$numeric,'nonblank'=>$nonblank,'zero'=>$zero,'positive'=>$positive,'max'=>$max];}if(!$scores)return null;usort($scores,fn($a,$b)=>$b['score']<=>$a['score']);$best=$scores[0];if(isset($scores[1])&&abs($best['score']-$scores[1]['score'])<25&&$best['index']!==11)return null;return $best;}
function authImport(array $config):void{$g=(string)($_SERVER['HTTP_X_IMPORT_TOKEN']??'');$e=(string)($config['import_token']??'');if($e!==''&&$g!==''&&hash_equals($e,$g))return;require_admin();if($_SERVER['REQUEST_METHOD']==='POST')csrf_check();}
function findFiles(string $root):array{$p=[];$c=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile()||strtolower($f->getExtension())!=='csv')continue;$n=mb_strtolower($f->getFilename());$x=['p'=>$f->getPathname(),'s'=>$f->getSize(),'m'=>$f->getMTime()];if(str_contains($n,'tovary'))$p[]=$x;elseif(str_contains($n,'categor'))$c[]=$x;}$pick=function(array $a):?string{if(!$a)return null;usort($a,fn($x,$y)=>($y['s']<=>$x['s'])?:($y['m']<=>$x['m']));return $a[0]['p'];};return[$pick($p),$pick($c)];}
function imageIndex(string $root,int $offset):array{$cache=__DIR__.'/../uploads/1c-image-index.json';if($offset>0&&is_file($cache)){$j=json_decode((string)file_get_contents($cache),true);if(is_array($j)&&isset($j['map']))return[$j['map'],(int)($j['count']??count($j['map']))];}$map=[];$count=0;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile())continue;$e=strtolower($f->getExtension());if(!in_array($e,['jpg','jpeg','png','webp','gif','avif'],true))continue;$count++;$map[mb_strtolower($f->getFilename())]=str_replace(DIRECTORY_SEPARATOR,'/',substr($f->getPathname(),strlen($root)+1));}if(!is_dir(dirname($cache)))@mkdir(dirname($cache),0755,true);@file_put_contents($cache,json_encode(['count'=>$count,'map'=>$map],JSON_UNESCAPED_SLASHES));return[$map,$count];}
function photoUrls(string $cell,array $idx):array{$out=[];foreach(preg_split('/[|,\r\n]+/u',$cell)?:[] as $x){$x=mb_strtolower(basename(str_replace('\\','/',trim($x," \t\"'"))));if($x!==''&&isset($idx[$x]))$out[]='/import/'.$idx[$x];}return array_values(array_unique($out));}
function money(string $x):float{$x=str_replace(',','.',preg_replace('/[^0-9,.-]/u','',$x)??'');return is_numeric($x)?(float)$x:0.0;}
function slugify(string $s,string $fallback):string{$s=mb_strtolower(trim($s));$s=preg_replace('/[^a-zа-я0-9]+/u','-',$s)??'';$s=trim($s,'-');return $s!==''?$s:$fallback;}
try{
 authImport($config);if($_SERVER['REQUEST_METHOD']!=='POST')throw new RuntimeException('post_required');
 $root=realpath(__DIR__.'/../import');if(!$root)throw new RuntimeException('import_missing');[$pf,$cf]=findFiles($root);if(!$pf||!$cf)throw new RuntimeException('1c_csv_missing');
 $rows=csvRows($pf);$catsRaw=csvRows($cf);if(!$rows)throw new RuntimeException('Файл товаров 1С пуст.');
 $firstMap=headerMap($rows[0]);$hasHeader=count($firstMap)>=2;$map=$hasHeader?$firstMap:['category'=>3,'source_id'=>4,'sku'=>5,'name'=>7,'image'=>9,'price'=>10];
 if($hasHeader){$stockIndex=$map['stock']??null;if($stockIndex===null)throw new RuntimeException('В выгрузке 1С не найдена колонка остатка.');$stockHeader=trim((string)($rows[0][$stockIndex]??'Остаток'));array_shift($rows);}else{$det=detectStockColumn($rows,[0,1,2,3,4,5,6,7,8,9,10]);if(!$det)throw new RuntimeException('Не удалось безопасно определить колонку остатка в выгрузке без заголовков. Данные не изменены.');$stockIndex=(int)$det['index'];$stockHeader='авто: колонка '.($stockIndex+1);}
 $productRows=0;$validStockRows=0;$invalidStockRows=0;foreach($rows as $rr){$name=trim((string)($rr[$map['name']]??''));if($name===''&&!$hasHeader)$name=trim((string)($rr[6]??''));if($name==='')continue;$productRows++;$q=stockQty((string)($rr[$stockIndex]??''));if($q===null)$invalidStockRows++;else$validStockRows++;}
 if($productRows===0)throw new RuntimeException('В выгрузке не найдены товарные строки.');
 $invalidLimit=max(5,(int)ceil($productRows*.001));if($invalidStockRows>$invalidLimit)throw new RuntimeException('Колонка остатка определена как «'.$stockHeader.'», но у '.$invalidStockRows.' товаров остаток пустой или некорректный. Это больше безопасного порога '.$invalidLimit.'. Импорт остановлен до изменения базы.');
 $total=count($rows);$offset=max(0,(int)($_GET['offset']??0));$limit=min(1000,max(100,(int)($_GET['limit']??500)));$slice=array_slice($rows,$offset,$limit);
 $cats=[];foreach($catsRaw as $r){$id=trim((string)($r[0]??''));$name=trim((string)($r[1]??''));if($id===''||$name==='')continue;$cats[$id]=['name'=>$name,'parent'=>trim((string)($r[2]??'') )];}
 $catPath=function(string $id)use(&$cats):string{$parts=[];$seen=[];while($id!==''&&isset($cats[$id])&&!isset($seen[$id])){$seen[$id]=1;array_unshift($parts,$cats[$id]['name']);$id=(string)($cats[$id]['parent']??'');}return implode(' / ',$parts);};
 [$imgIndex,$imageFiles]=imageIndex($root,$offset);
 $bySource=$pdo->prepare('SELECT * FROM products WHERE source_id=? LIMIT 1');$byHash=$pdo->prepare('SELECT * FROM products WHERE source_hash=? LIMIT 1');$byName=$pdo->prepare('SELECT * FROM products WHERE name=? ORDER BY is_active DESC,id DESC LIMIT 1');
 $ins=$pdo->prepare('INSERT INTO products(source_id,source_hash,name,slug,sku,price,price_rub,stock_qty,stock_status,availability,category_path,main_image,images,is_active,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())');
 $upd=$pdo->prepare('UPDATE products SET source_id=?,source_hash=?,name=?,slug=?,sku=?,price=?,price_rub=?,stock_qty=?,stock_status=?,availability=?,category_path=?,main_image=?,images=?,is_active=?,updated_at=NOW() WHERE id=?');
 $created=$updated=$rowsWithPhoto=$photosLinked=$stockMapped=$zeroStock=$positiveStock=$archived=$restored=0;$pdo->beginTransaction();
 foreach($slice as $r){$sourceIdx=$map['source_id'];$skuIdx=$map['sku'];$nameIdx=$map['name'];$categoryIdx=$map['category'];$priceIdx=$map['price'];$imageIdx=$map['image'];$sourceId=trim((string)($r[$sourceIdx]??''));$sku=trim((string)($r[$skuIdx]??''));$name=trim((string)($r[$nameIdx]??''));if($name===''&&!$hasHeader)$name=trim((string)($r[6]??''));if($name==='')continue;$qty=stockQty((string)($r[$stockIndex]??''));if($qty===null)$qty=0;$stockMapped++;$stockStatus=$qty>0?'in_stock':'out_of_stock';$active=$qty>0?1:0;if($qty>0)$positiveStock++;else$zeroStock++;$hash=hash('sha256','1c|'.($sourceId!==''?$sourceId:json_encode($r,JSON_UNESCAPED_UNICODE)));$price=money((string)($r[$priceIdx]??''));$priceRub=(int)round($price);$category=$catPath((string)($r[$categoryIdx]??''));$urls=photoUrls((string)($r[$imageIdx]??''),$imgIndex);if($urls){$rowsWithPhoto++;$photosLinked+=count($urls);}$existing=false;if($sourceId!==''){$bySource->execute([$sourceId]);$existing=$bySource->fetch();}if(!$existing){$byHash->execute([$hash]);$existing=$byHash->fetch();}if(!$existing){$byName->execute([$name]);$existing=$byName->fetch();}$existingImages=[];if($existing&&!empty($existing['images']))$existingImages=json_decode((string)$existing['images'],true)?:[];$finalImages=$urls?:$existingImages;$main=$finalImages[0]??($existing['main_image']??null);$slug=$existing['slug']??slugify($name,'product-'.$sourceId);$imagesJson=json_encode($finalImages,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($existing){$wasActive=(int)($existing['is_active']??1);$upd->execute([$sourceId?:($existing['source_id']??null),$hash,$name,$slug,$sku?:($existing['sku']??null),$price,$priceRub,$qty,$stockStatus,$stockStatus,$category?:($existing['category_path']??''),$main,$imagesJson,$active,(int)$existing['id']]);if($wasActive===1&&$active===0)$archived++;if($wasActive===0&&$active===1)$restored++;$updated++;}else{$ins->execute([$sourceId?:null,$hash,$name,$slug,$sku?:null,$price,$priceRub,$qty,$stockStatus,$stockStatus,$category,$main,$imagesJson,$active]);$created++;if($active===0)$archived++;}}
 $pdo->commit();$next=$offset+count($slice);$done=$next>=$total;if($done){$categoryPayload=[];foreach($cats as $id=>$c)$categoryPayload[]=['id'=>(string)$id,'name'=>$c['name'],'parent'=>(string)$c['parent'],'path'=>$catPath((string)$id)];$meta=['file'=>basename($pf),'rows'=>$total,'product_rows'=>$productRows,'category_rows'=>count($cats),'image_files'=>$imageFiles,'header_mode'=>$hasHeader?'named':'headerless','stock_column'=>$stockHeader,'stock_valid_rows'=>$validStockRows,'stock_invalid_rows'=>$invalidStockRows,'stock_invalid_treated_as_zero'=>$invalidStockRows,'finished_at'=>date('c')];$s=$pdo->prepare("INSERT INTO site_settings(setting_key,setting_value) VALUES('last_1c_import',?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");$s->execute([json_encode($meta,JSON_UNESCAPED_UNICODE)]);$s=$pdo->prepare("INSERT INTO site_settings(setting_key,setting_value) VALUES('1c_categories',?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");$s->execute([json_encode($categoryPayload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);audit($pdo,'import_1c_complete','products',null,$meta);}
 out(['ok'=>true,'source'=>basename($pf),'category_source'=>basename($cf),'header_mode'=>$hasHeader?'named':'headerless','stock_column'=>$stockHeader,'offset'=>$offset,'processed'=>count($slice),'total_rows'=>$total,'created'=>$created,'updated'=>$updated,'rows_with_photo'=>$rowsWithPhoto,'photos_linked'=>$photosLinked,'stock_column_found'=>true,'stock_mapped'=>$stockMapped,'unknown_stock'=>$invalidStockRows,'zero_stock'=>$zeroStock,'positive_stock'=>$positiveStock,'archived'=>$archived,'restored'=>$restored,'category_rows'=>count($cats),'image_files'=>$imageFiles,'next_offset'=>$next,'done'=>$done]);
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log($e->__toString());out(['ok'=>false,'error'=>$e->getMessage()],500);}